### ISSUE TITLE
赚京豆小程序无法助力

### ISSUE THREAD

**Issue by limoruirui** [wisz2021/jd_docker#105]
环境：debian10 docker-compose 镜像版本是5月8日的 容器id跟置顶那个一样 3f42d831cb2a
之前是可以的 就最近大概半个月不行了，显示活动火爆 跳出
手动点是可以的
![赚京豆](https://user-images.githubusercontent.com/45648638/117527536-6cb11d00-afff-11eb-96a5-a1bfef57a93a.jpg)
![赚京豆1](https://user-images.githubusercontent.com/45648638/117527551-805c8380-afff-11eb-9f2b-4ebc82227fef.jpg)

**Comment by limoruirui** [comment]
看了一下之前下载的日志 就是4月27号更新了jd_syj.js之后无法助力的

**Comment by limoruirui** [comment]
测了4月20号的syj脚本 可以正常助力

**Comment by fuhuo8** [comment]
> 测了4月20号的syj脚本 可以正常助力

麻烦大佬发一份旧版本，谢谢，fuhuo8@qq.com

**Comment by limoruirui** [comment]
20号的版本不能正常开团 用前天12号更新的版本可以正常助力了 更新就行 关闭issue
