### ISSUE TITLE
bot使用/bean返回图片不完整

### ISSUE THREAD

**Issue by harrison-guo-chn** [wisz2021/jd_docker#109]
这是我自己的设备部署的使用命令后返回的图片，返回的图片并不完整。
![IMG_20210508_192141_947](https://user-images.githubusercontent.com/58265745/117538544-47d99b80-b039-11eb-89d5-303164de10c1.jpg)

这是别人的，返回的图片就没有问题
![IMG_20210508_200449_141](https://user-images.githubusercontent.com/58265745/117538559-57f17b00-b039-11eb-85fc-3a94bc865acd.jpg)

请问如何能解决这个错误

**Comment by WinterBoring** [comment]
我也是这样！只有一截

**Comment by harrison-guo-chn** [comment]
> 我也是这样！只有一截

log文件夹有csv后缀的文件，全部删掉就正常了
