### ISSUE TITLE
logs目录下没有自动生成cookie.list文件，怎么办

### ISSUE THREAD

**Issue by lonercci** [wisz2021/jd_docker#117]
每次在docker-compose.yml里面添加新的cookie，都需要docker-compose up -d。。
我人别人的教程，好像会自动生成一个cookie.list文件，直接在里面添加就好了，不用每次启动
但是我的logs目录下没有生成这个文件，请问该怎么办呢，需要手动新建这个文件吗
求教各位大大们

**Comment by lockingxp** [comment]
https://github.com/wisz2021/jd_docker/tree/main/docker

**Comment by wisz2021** [comment]
满足条件后。开启了bot交互 才有此cookie.list文件

条件为：可科学上网的网络环境。tgbot通知的token 和ID
