### ISSUE TITLE
求助取关变量

### ISSUE THREAD

**Issue by woboo110** [wisz2021/jd_docker#119]
求助，现在取关变量如何填了？默认是全部取关

**Comment by wisz2021** [comment]
例如1：不要取关任何商品和店铺，则输入0&0 

例如2：我想商品遇到关键字 iPhone12 停止取关，店铺遇到 Apple京东自营旗舰店 不再取关，则输入10&10&iPhone12&Apple京东自营旗舰店(前面两个参数非0即可)

**Comment by wisz2021** [comment]
> > 这不是有说明吗
> > jd_docker/githubAction.md at main · wisz2021/jd_docker
> > https://github.com/wisz2021/jd_docker/blob/main/githubAction.md#%E5%8F%96%E5%85%B3%E5%BA%97%E9%93%BA%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%E7%9A%84%E8%AF%B4%E6%98%8E
> 
> 这样写？ UN_SUBSCRIBES="30&40"

不带双引号。我仓库docker

**Comment by woboo110** [comment]
> > > 这不是有说明吗
> > > jd_docker/githubAction.md at main · wisz2021/jd_docker
> > > https://github.com/wisz2021/jd_docker/blob/main/githubAction.md#%E5%8F%96%E5%85%B3%E5%BA%97%E9%93%BA%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%E7%9A%84%E8%AF%B4%E6%98%8E
> > 
> > 
> > 这样写？ UN_SUBSCRIBES="30&40"
> 
> 不带双引号。我仓库docker

多谢大佬
