### ISSUE TITLE
45 */2,23 * * * node /scripts/jd_joy.js crontab格式写错了

### ISSUE THREAD

**Issue by evan766** [wisz2021/jd_docker#120]
# 宠汪汪
45 */2,23 * * * node /scripts/jd_joy.js >> /scripts/logs/jd_joy.log 2>&1
# 宠汪汪积分兑换京豆

**Comment by limoruirui** [comment]
没错 */2,23是表示小时 整体表示(每天双数小时和单数小时的23点)的45分运行

**Comment by start0325** [comment]
哪错了？

**Comment by lockingxp** [comment]
https://crontab.guru/#45_*/2,23_*_*_*

**Comment by wisz2021** [comment]
没错的

**Comment by evan766** [comment]
*/2,23 应该没有这种写法，估计你是手快写错了，可以找个解析crontab网站贴上去看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月10日(周一) 中午1:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wisz2021/jd_docker] 45 */2,23 * * * node /scripts/jd_joy.js crontab格式写错了 (#120)




 
哪错了？

**Comment by evan766** [comment]
还有这种写法，抱歉，我去深入了解一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月10日(周一) 中午11:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wisz2021/jd_docker] 45 */2,23 * * * node /scripts/jd_joy.js crontab格式写错了 (#120)




 
没错 */2,23是表示小时 整体表示(每天双数小时和单数小时的23点)的45分运行

**Comment by limoruirui** [comment]
> */2,23 应该没有这种写法，估计你是手快写错了，可以找个解析crontab网站贴上去看看
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年5月10日(周一) 中午1:18 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [wisz2021/jd_docker] 45 */2,23 * * * node /scripts/jd_joy.js crontab格式写错了 (#120) 哪错了？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

真的没问题 不要过于执着在线网站 写网站的人不一定懂所有人的想法 直接自己去试一次就知道这种表达能不能完成了

**Comment by evan766** [comment]
好的，谢谢。估计我他也是跟我一样水平



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月12日(周三) 晚上8:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wisz2021/jd_docker] 45 */2,23 * * * node /scripts/jd_joy.js crontab格式写错了 (#120)




  
/2,23 应该没有这种写法，估计你是手快写错了，可以找个解析crontab网站贴上去看看
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年5月10日(周一) 中午1:18 收件人: @.&gt;; 抄送: @.@.*&gt;; 主题: Re: [wisz2021/jd_docker] 45 */2,23 * * * node /scripts/jd_joy.js crontab格式写错了 (#120) 哪错了？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
真的没问题 不要过于执着在线网站 写网站的人不一定懂所有人的想法 直接自己去试一次就知道这种表达能不能完成了
