### ISSUE TITLE
账号提示header content 是不是凉了

### ISSUE THREAD

**Issue by shenmadouyaowen** [wisz2021/jd_docker#122]
大神，我有一个账号提示Invalid character in header content [\"cookie\"]，重新扫描也是一样，其他账号没事，这个账号是不是不能挂机了？

**Comment by lockingxp** [comment]
cookie错了 你这里面有中文

**Comment by shenmadouyaowen** [comment]
> 饼干小马奇

是的,检测出来了,我自己手贱在后面加注释,然后把注释也带上了
