### ISSUE TITLE
请教一下口袋书店这个京东的入口在哪里？

### ISSUE THREAD

**Issue by dnxbice** [wisz2021/jd_docker#123]
RT，一直找不到这个活动的入口，请教大家在哪里找到的？

**Comment by woboo110** [comment]
京东图书

**Comment by limoruirui** [comment]
京东app首页-中间的那些板块-往右划找京东图书-右下角会有个活动点进去就是 不过好像这活动也没什么收益

**Comment by dnxbice** [comment]
> 京东app首页-中间的那些板块-往右划找京东图书-右下角会有个活动点进去就是就是好像好像该活动也没什么收益

很感谢你的回复 但是我还没有找到这个入口 如图所示 我打开以后就是这样呢 我了不是非要多少收益  我只是不想看到日志里总显示失败呢
![微信图片_20210510133556](https://user-images.githubusercontent.com/24774919/117610742-d282dd80-b194-11eb-8fec-9a6880a58dfa.jpg)

**Comment by woboo110** [comment]
右上角签到，点进去，下面每日参与活动

**Comment by Rexexe** [comment]
25.0复制整段话 Http:/Jso0UrWoVJI8Cy开了家书店~#nEaqF9Aeqb%→去&#120051;&#120050;&#120055;&#120048;腖Ap p

入口不好找了，复制分享码进吧

**Comment by dnxbice** [comment]
> 右上角签到，点进去，下面每日参与活动

非常感谢
