### ISSUE TITLE
签到领现金换京豆

### ISSUE THREAD

**Issue by xieguapi** [wisz2021/jd_docker#13]
大佬可以整个变量控制一下吗，想攒钱提现
![image](https://user-images.githubusercontent.com/46696341/116515060-65528b00-a8fe-11eb-9011-c7c93e90efd7.png)

**Comment by q123458384** [comment]
看教程啊~
|    `CASH_EXCHANGE`    |     京东领现金<br>红包兑换京豆开关     | 非必须 | 控制京东领现金是否把红包兑换成京豆,<br>`false`为否,`true`为是(即：花费2元红包兑换200京豆，一周可换四次)，默认为`true` |

**Comment by xieguapi** [comment]
> 看教程啊~
> | `CASH_EXCHANGE` | 京东领现金
> 红包兑换京豆开关 | 非必须 | 控制京东领现金是否把红包兑换成京豆,
> `false`为否,`true`为是(即：花费2元红包兑换200京豆，一周可换四次)，默认为`true` |

在哪里看的老哥，真没看到

**Comment by q123458384** [comment]
> > 看教程啊~
> > | `CASH_EXCHANGE` | 京东领现金
> > 红包兑换京豆开关 | 非必须 | 控制京东领现金是否把红包兑换成京豆,
> > `false`为否,`true`为是(即：花费2元红包兑换200京豆，一周可换四次)，默认为`true` |
> 
> 在哪里看的老哥，真没看到

容器内：```
cat /jd/scripts/githubAction.md
```

**Comment by xieguapi** [comment]
> > > 看教程啊~
> > > | `CASH_EXCHANGE` | 京东领现金
> > > 红包兑换京豆开关 | 非必须 | 控制京东领现金是否把红包兑换成京豆,
> > > `false`为否,`true`为是(即：花费2元红包兑换200京豆，一周可换四次)，默认为`true` |
> > 
> > 
> > 在哪里看的老哥，真没看到
> 
> 容器内：```
> cat /jd/scripts/githubAction.md

好的感谢
