### ISSUE TITLE
赚京豆一直开团人数不满

### ISSUE THREAD

**Issue by lhc13145** [wisz2021/jd_docker#137]
catch 赚京豆团邀请码提交异常:Timeout awaiting 'request' for 30000ms
May 11 14:14:39 catch 赚京豆团邀请码提交异常:Timeout awaiting 'request' for 30000ms
May 11 14:14:40 catch 赚京豆团邀请码提交异常:Timeout awaiting 'request' for 30000ms
May 11 14:14:41 catch 赚京豆团邀请码提交异常:Timeout awaiting 'request' for 30000ms
May 11 14:14:42 catch 赚京豆团邀请码提交异常:Timeout awaiting 'request' for 30000ms
May 11 14:14:42 catch 赚京豆团邀请码提交异常:Timeout awaiting 'request' for 30000ms
号内部互助不是火爆，就是没满人。

**Comment by ppdown123** [comment]
我也是这样，不知怎么解

**Comment by wisz2021** [comment]
火爆问题， 暂时修复了一下。
