### ISSUE TITLE
使用docker-compose部署后更改docker-compose.yml无效

### ISSUE THREAD

**Issue by snowman32** [wisz2021/jd_docker#143]
就是第一次运行后就定型了，要改docker-compose.yml里面东西也无效
现在绑定TGBOT后只能运行最初的那个CK，cookies.list中添加第二个CK，重启docker，还是一个CK
确定TGBOG绑定成功了。请大佬解答

**Comment by lockingxp** [comment]
请认真阅读文档https://github.com/wisz2021/jd_docker/blob/main/docker/Readme.md

**Comment by BlueSpiderGIGI** [comment]
docker-compose stop 再 docker-compose up -d
或者修改后docker-compose up -d

**Comment by hzexe** [comment]
我每次都是down-rm-pull-start
也有阴影,改过cookie后还提示过期,总感觉像是没生效一样..反正用上面一堆,才能心安

**Comment by zhangfangbiao** [comment]
修改yml配置文件后需要docker-compose up -d重新启动容器，请熟读并背诵文档。
