### ISSUE TITLE
npm 安装错误

### ISSUE THREAD

**Issue by hello1983** [wisz2021/jd_docker#147]
err: npm WARN ws@7.4.5 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself. 27 err: npm WARN ws@7.4.5 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself. 28 err:

**Comment by BlueSpiderGIGI** [comment]
npm install -g nmp 就好了，但是重启容器后就会恢复告警，毕竟镜像里的是老的。

**Comment by sw19999** [comment]
这个有什么影响呢？我没有升级好像也可以用，不过我没有开启任何一种通知消息

**Comment by BlueSpiderGIGI** [comment]
不升级好像感觉到什么影响
