### ISSUE TITLE
请问大佬京东app连续退出，cookie也失效了

### ISSUE THREAD

**Issue by snowtank** [wisz2021/jd_docker#148]
这是啥原因?谢谢

**Comment by fengmikaelson** [comment]
应该是京东方面的账号检测之类的~

重登陆就好了，我12个账号有2个出现这个情况。

**Comment by 275244143** [comment]
> 应该是京东方面的账号检测之类的~
> 
> 重登陆就好了，我12个账号有2个出现这个情况。

不停的失效，如何解决？

**Comment by drw2005** [comment]
我这两天也出现一直提示cookie失效。。。更新了也不行。

**Comment by fengmikaelson** [comment]
> > 应该是京东方面的账号检测之类的~
> > 重登陆就好了，我12个账号有2个出现这个情况。
> 
> 不停的失效，如何解决？

那我就没遇到了，我退出了一次，更新了就好了。
