### ISSUE TITLE
为什么2个同样的容器配置，一个会有签到统计通知，一个没有。

### ISSUE THREAD

**Issue by fengmikaelson** [wisz2021/jd_docker#150]
群晖 docker部署。从某一次更新之后就出现了这个情况。一样的配置，一个会有 每日多合一签到通知，一个没有。
![1](https://user-images.githubusercontent.com/10394327/117903702-9bcad580-b302-11eb-966a-27601793fb13.png)
![2](https://user-images.githubusercontent.com/10394327/117903782-c026b200-b302-11eb-9e2f-04f5d456017a.png)

**Comment by BlueSpiderGIGI** [comment]
关于这个推送我也觉得是个迷，我也是有很多不推送

**Comment by fengmikaelson** [comment]
> 关于这个推送我也觉得是个迷，我也是有很多不推送

啊这~以前都正常的，从某一次更新开始就这样了。。。

**Comment by wisz2021** [comment]
多合一签到。 默认是有通知的， 没有通知。 就去查看日志呀，  jd_bean_sign.log

**Comment by fengmikaelson** [comment]
> 多合一签到。 默认是有通知的， 没有通知。 就去查看日志呀， jd_bean_sign.log

日志是有，但是就是不通知，哈哈，有点奇怪。因为另一个每天都会通知。。。

毕竟通知比手动去查更省时呀。

**Comment by wisz2021** [comment]
。。。我的意思是看发生通知的原因。

**Comment by wisz2021** [comment]
以后没有日志。不要发issue。自己解决这个问题吧。 看最底部发生通知失败的日子

**Comment by fengmikaelson** [comment]
> 以后没有日志。不要发issue。自己解决这个问题吧。 看最底部发生通知失败的日子

是这个日志吗。。。我看另一个正常通知的，最底部也是这样报错。。。
![image](https://user-images.githubusercontent.com/10394327/118418949-1e7dd700-b6ed-11eb-830b-4d9683a49da5.png)
