### ISSUE TITLE
内存占用逐渐升高，然后CPU100% 硬盘读取爆了

### ISSUE THREAD

**Issue by syouko** [wisz2021/jd_docker#152]
配置：
1C 1G，后来换了1C 2G
腾讯云 Debian 10.2

容器是三开，每个容器里20个账号不到。

大概每隔几天每个容器的内存就会从刚开始的100M不到逐渐上升到400甚至500M，然后内存接近占满。

之后就失联了，SSH VNC都上不去。

通过腾讯云后台的资源监控看到CPU一直满载，内存处于很高的位置 90%左右。

硬盘读取速率突然升高，时间点在0点的时候

![image](https://user-images.githubusercontent.com/19810171/117916966-c2950600-b31a-11eb-9687-9422e79a17b1.png)

不知是什么原因

**Comment by 275244143** [comment]
做个定期任务，kill jd 进程~ ~，

**Comment by scolyp** [comment]
同问如何脚本运行时降低内存
