### ISSUE TITLE
lxk0301/jd_scripts:5.12    启动失败.

### ISSUE THREAD

**Issue by colloq168** [wisz2021/jd_docker#156]
docker-compose.yml没任何的改动, 之前都能正常启动. 

一下是报错信息:

# docker-compose down
ERROR: The Compose file './docker-compose.yml' is invalid because:
jd.environment contains non-unique items, please remove duplicates from ['REPO_URL=git@gitee.com:lxk0301/jd_scripts.git', 'JD_COOKIE=pt_key=已填写', 'QYWX_AM=已填写', 'JD_BEAN_SIGN_NOTIFY_SIMPLE=true', 'ENABLE_AUTO_HELP=true', 'JOY_FEED_COUNT=80', 'JOY_HELP_FEED=true', 'JOY_RUN_FLAG=true', 'JOY_TEAM_LEVEL=2', 'JOY_RUN_NOTIFY=true', 'JOY_RUN_HELP_MYSELF=true', 'JD_JOY_REWARD_NAME=20', 'MARKET_COIN_TO_BEANS=20', 'FRUIT_BEAN_CARD=false', 'JDJOY_HELPSELF=true', 'JD_JXD_EXCHANGE=true', 'JDJOY_APPLYJDBEAN=2000', 'MONEY_TREE_SELL_FRUIT=true', 'CRZAY_JOY_COIN_ENABLE=Y', 'JD_JXD_EXCHANGE=true', 'SHARE_CODE_FILE=/scripts/logs/sharecode.log']

**Comment by lockingxp** [comment]
复现实验证明你的描述不对，问题的原因是yml中有重复，绝对不会是没有改动
![微信图片_20210513031320](https://user-images.githubusercontent.com/64940622/118031504-238dff80-b356-11eb-8890-06092f806d45.png)
![微信截图_20210513031111](https://user-images.githubusercontent.com/64940622/118031507-24269600-b356-11eb-853f-38eb1a21cf76.png)

**Comment by colloq168** [comment]
JD_COOKIE   QYWX_AM   我都填写啦, 为了安全起见没填上去.

**Comment by colloq168** [comment]
![image](https://user-images.githubusercontent.com/12294096/118062702-1dd20180-b3ca-11eb-81fe-2583de079c2c.png)

**Comment by colloq168** [comment]
找到啦.    JD_JXD_EXCHANGE      重复啦
