### ISSUE TITLE
健康社区脚本执行报错

### ISSUE THREAD

**Issue by BlueSpiderGIGI** [wisz2021/jd_docker#161]
images：160a62df5141
脚本：jd_health.js、jd_health_collect.js

/scripts # node jd_health.js
/scripts/jd_health.js:106
    if([108,-1001].includes(res?.data?.bizCode)){
                                              ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
/scripts #

**Comment by lockingxp** [comment]
https://github.com/wisz2021/jd_docker/issues/157#issuecomment-840235972

**Comment by BlueSpiderGIGI** [comment]
感谢，mark一下
apk add nodejs-current
问题是我已经是拉的最新的160a62df5141版本的镜像了

**Comment by drw2005** [comment]
> 感谢，mark一下
> apk add nodejs-current
> 问题是我已经是拉的最新的160a62df5141版本的镜像了
我也是这个版本的镜像，也是一直报这个错，兄弟解决了没有？

**Comment by BlueSpiderGIGI** [comment]
> > 感谢，mark一下
> > apk add nodejs-current
> > 问题是我已经是拉的最新的160a62df5141版本的镜像了
> 
> 我也是这个版本的镜像，也是一直报这个错，兄弟解决了没有？

上面不写了吗，apk add nodejs-current

**Comment by ssrgd** [comment]
我原本也有这个问题，然后新建容器之后就没了，感觉有点玄学

**Comment by BlueSpiderGIGI** [comment]
> [#157 (comment)](https://github.com/wisz2021/jd_docker/issues/157#issuecomment-840235972)

问问怎么解决重启容器就要重新安装的难题

**Comment by wisz2021** [comment]
> > [#157 (comment)](https://github.com/wisz2021/jd_docker/issues/157#issuecomment-840235972)
> 
> 问问怎么解决重启容器就要重新安装的难题

up -d 本意就是
