### ISSUE TITLE
资产变动通知数据异常

### ISSUE THREAD

**Issue by Ruyenet** [wisz2021/jd_docker#162]
![`QL1G(TRA2BS $4{ 4$I5 U](https://user-images.githubusercontent.com/31236859/118069768-56c4a300-b3d7-11eb-93a2-68711a6f1b27.png)

**Comment by fengmikaelson** [comment]
为什么我的没这个通知，手动开启的吗？

**Comment by gebaolei** [comment]
刚加入的账号有时会报错，第二天就好了

**Comment by Ruyenet** [comment]
> 刚加入的账号有时会报错，第二天就好了

昨天5月12日下午加入的，今天5月13日上午看了还是报错，不知道明天会怎样

**Comment by z594024037** [comment]
半小时前遇到了同样的问题，插眼等后续

**Comment by Ruyenet** [comment]
> 半小时前遇到了同样的问题，插眼等后续

等到第三天，正常了

**Comment by z594024037** [comment]
> > 半小时前遇到了同样的问题，插眼等后续
> 
> 
> 
> 等到第三天，正常了

我今天是第二天 还没有正常推送 明天康康吧😂

**Comment by drw2005** [comment]
我的最近几天也没有推送，不知道啥原因。

**Comment by z594024037** [comment]
我的今天第三天也正常了

**Comment by wisz2021** [comment]
新号。或者很久没有京豆支出收入会出现此问题

**Comment by drw2005** [comment]
> 新号。或者很久没有京豆支出收入会出现此问题

我确实很久没有京豆支出了
