### ISSUE TITLE
怎样才能手动运行全部脚本呀

### ISSUE THREAD

**Issue by 04wyt** [wisz2021/jd_docker#163]
首次安装之后想手动运行一下所有脚本，但是不知道命令

**Comment by 275244143** [comment]
docker exec -it jd_scripts /bin/sh -c 'ls jd_*.js |xargs -i node {}'

**Comment by satan1410** [comment]
有大佬能告诉下群辉docker里怎么执行？   用上面那个命令总是说jd_*.js文件名不存在

**Comment by 275244143** [comment]
> 有大佬能告诉下群辉docker里怎么执行？ 用上面那个命令总是说jd_*.js文件名不存在

docker exec -it jd_scripts /bin/sh -c 'cd /scripts;ls jd_*.js' 如果没有就是路径有问题。

**Comment by adnimzby** [comment]
> docker exec -it jd_scripts /bin/sh -c 'ls jd_*.js |xargs -i node {}'
运行了这个发现一直循环crazyjoy 看了下是因为jd_crazy_joy_coin.js这个脚本
这样就好了docker exec -it jd_scripts /bin/sh -c ' ls jd_*.js | grep -v jd_crazy_joy_coin.js |xargs -i node {}'

**Comment by C-racker** [comment]
> > 有大佬能告诉下群辉docker里怎么执行？ 用上面那个命令总是说jd_*.js文件名不存在
> 
> docker exec -it jd_scripts /bin/sh -c 'cd /scripts;ls jd_*.js' 如果没有就是路径有问题。

多容器如何执行所有呢
