### ISSUE TITLE
助力问题，我明明设置了助力码，日志也有提示设置助力成功

### ISSUE THREAD

**Issue by ss18873310** [wisz2021/jd_docker#166]
助力问题，我明明设置了助力码，日志也有提示设置助力成功，
但是就是没有助力，农场，工厂，需要助力所有的活动都没有助力，
我的是群晖安装的docker ,这次总是自动意外关闭docker容器里的jd。我就删除从新安装，在这之前我设置的助力码完全可以助力，而且还互助。新安装后填写的互助码也不助力了，几个账号也不互助了。
![image](https://user-images.githubusercontent.com/25823769/118078263-60a2d200-b3e8-11eb-92a0-f730ea9d670c.png)
明明是提供了助力码，后面的账号却提示没有提供助力码。

**Comment by fengmikaelson** [comment]
你直接把自动互助开起来看看咯

**Comment by ss18873310** [comment]
> 你直接把自动互助开起来看看咯

怎么把自动互助打开呢？

**Comment by ss18873310** [comment]
今天晚上还是不行，也不互助，也不助力我设置的互助码

**Comment by fengmikaelson** [comment]
> > 你直接把自动互助开起来看看咯
> 
> 怎么把自动互助打开呢？

都不看文档说明的嘛= = 全部都写了

**Comment by ss18873310** [comment]
> > > 你直接把自动互助开起来看看咯
> > 
> > 
> > 怎么把自动互助打开呢？
> 
> 都不看文档说明的嘛= = 全部都写了

哥哥，您要是知道就给说一下，您要说文档我没看就冤枉人了。我确实看了，可能没有看到互助文档这一块，而且在发问题前我又从新看了一遍，所以才求助的，麻烦您把关于互助这一块的文档给说明一下。

**Comment by zhangbing317** [comment]
ENABLE_AUTO_HELP=true

**Comment by ss18873310** [comment]
> ENABLE_AUTO_HELP=true

谢谢，，，

**Comment by ss18873310** [comment]
> ENABLE_AUTO_HELP=true

这位哥，知道我设置了助力码，为啥都不助力吗？

**Comment by ss18873310** [comment]
> > > > 你直接把自动互助开起来看看咯
> > > 
> > > 
> > > 怎么把自动互助打开呢？
> > 
> > 
> > 都不看文档说明的嘛= = 全部都写了
> 
> 哥哥，您要是知道就给说一下，您要说文档我没看就冤枉人了。我确实看了，可能没有看到互助文档这一块，而且在发问题前我又从新看了一遍，所以才求助的，麻烦您把关于互助这一块的文档给说明一下。


> > > > 你直接把自动互助开起来看看咯
> > > 
> > > 
> > > 怎么把自动互助打开呢？
> > 
> > 
> > 都不看文档说明的嘛= = 全部都写了
> 
> 哥哥，您要是知道就给说一下，您要说文档我没看就冤枉人了。我确实看了，可能没有看到互助文档这一块，而且在发问题前我又从新看了一遍，所以才求助的，麻烦您把关于互助这一块的文档给说明一下。

确实是我没看到互助ENABLE_AUTO_HELP=true这个文档。确实是自己粗心大意，只盯着环境变量哪里去看了。这边的部署文档确实粗略看了一眼。

**Comment by fengmikaelson** [comment]
> > > > > 你直接把自动互助开起来看看咯
> > > > 
> > > > 
> > > > 怎么把自动互助打开呢？
> > > 
> > > 
> > > 都不看文档说明的嘛= = 全部都写了
> > 
> > 
> > 哥哥，您要是知道就给说一下，您要说文档我没看就冤枉人了。我确实看了，可能没有看到互助文档这一块，而且在发问题前我又从新看了一遍，所以才求助的，麻烦您把关于互助这一块的文档给说明一下。
> 
> > > > > 你直接把自动互助开起来看看咯
> > > > 
> > > > 
> > > > 怎么把自动互助打开呢？
> > > 
> > > 
> > > 都不看文档说明的嘛= = 全部都写了
> > 
> > 
> > 哥哥，您要是知道就给说一下，您要说文档我没看就冤枉人了。我确实看了，可能没有看到互助文档这一块，而且在发问题前我又从新看了一遍，所以才求助的，麻烦您把关于互助这一块的文档给说明一下。
> 
> 确实是我没看到互助ENABLE_AUTO_HELP=true这个文档。确实是自己粗心大意，只盯着环境变量哪里去看了。这边的部署文档确实粗略看了一眼。

https://github.com/wisz2021/jd_docker/tree/main/docker
https://github.com/wisz2021/jd_docker/blob/main/githubAction.md

所有文档类、配置类都在这里。

**Comment by ss18873310** [comment]
> > > > > > 你直接把自动互助开起来看看咯
> > > > > 
> > > > > 
> > > > > 怎么把自动互助打开呢？
> > > > 
> > > > 
> > > > 都不看文档说明的嘛= = 全部都写了
> > > 
> > > 
> > > 哥哥，您要是知道就给说一下，您要说文档我没看就冤枉人了。我确实看了，可能没有看到互助文档这一块，而且在发问题前我又从新看了一遍，所以才求助的，麻烦您把关于互助这一块的文档给说明一下。
> > 
> > 
> > > > > > 你直接把自动互助开起来看看咯
> > > > > 
> > > > > 
> > > > > 怎么把自动互助打开呢？
> > > > 
> > > > 
> > > > 都不看文档说明的嘛= = 全部都写了
> > > 
> > > 
> > > 哥哥，您要是知道就给说一下，您要说文档我没看就冤枉人了。我确实看了，可能没有看到互助文档这一块，而且在发问题前我又从新看了一遍，所以才求助的，麻烦您把关于互助这一块的文档给说明一下。
> > 
> > 
> > 确实是我没看到互助ENABLE_AUTO_HELP=true这个文档。确实是自己粗心大意，只盯着环境变量哪里去看了。这边的部署文档确实粗略看了一眼。
> 
> https://github.com/wisz2021/jd_docker/tree/main/docker
> https://github.com/wisz2021/jd_docker/blob/main/githubAction.md
> 
> 所有文档类、配置类都在这里。

谢谢。。。真心感谢。有时候一句提醒，真的能点醒。弄了一晚上真不如一句提醒。

**Comment by Hhhr99** [comment]
> ENABLE_AUTO_HELP=true

感谢
