### ISSUE TITLE
The authenticity of host 'github.com (13.229.188.59)' can't be established

### ISSUE THREAD

**Issue by crazyPerject** [wisz2021/jd_docker#167]
启动执行就报这个错误,然后就提示

默认定时任务执行完成

**Comment by gebaolei** [comment]
代码应该还是要从gitee上拉取

**Comment by crazyPerject** [comment]
> 代码应该还是要从gitee上拉取

gitee不是被删除了吗

**Comment by gebaolei** [comment]
> > 代码应该还是要从gitee上拉取
> 
> gitee不是被删除了吗

不是删除了，是私有了，不影响拉取代码

**Comment by gebaolei** [comment]
[ Photo ]
jd_docker项目昨天 (https://gitee.com/lxk0301/jd_docker)(2021/04/26)被封。

影响：非iOS使用者查看环境变量文档，仓库提issue，查看docker部署教程。

不影响：jd_scripts项目的脚本更新以及新增的脚本。

稍后发一份jd_docker仓库文件放频道。
