### ISSUE TITLE
用大佬的原版容器红包雨2个都提示火爆

### ISSUE THREAD

**Issue by zjgtree** [wisz2021/jd_docker#169]
但是用V4的几个号红包雨都能领到京豆，有人知道原因吗？

**Comment by kaikii98** [comment]
我的也是的，我找的另外一个大佬的文件用的

**Comment by jinpin** [comment]
原版红包雨正常啊，两个号

**Comment by zjgtree** [comment]
> 原版红包雨正常啊，两个号

但是这也太巧合了吧，就原版的提示火爆

**Comment by gebaolei** [comment]
> > 原版红包雨正常啊，两个号
> 
> 但是这也太巧合了吧，就原版的提示火爆

11号红包雨代码有更新，更新后应该是正常的，你看看是不是新版本

**Comment by wisz2021** [comment]
仓库的jd_live_redrain.js 原本是半点超级直播间的，偶尔夹杂了整点红包雨的。目前更新应该已正常。不会出现火爆问题
