### ISSUE TITLE
我的是原版的，怎么没有京东红包雨啊？

### ISSUE THREAD

**Issue by henanxiaoli** [wisz2021/jd_docker#172]
这脚本不是也更新着呢？怎么你们都有红包雨就我没有

**Comment by wisz2021** [comment]
jd_live_redrain.js 是晚上八点的超级直播间。 偶尔会有整点的红包雨

**Comment by wisz2021** [comment]
这是刚才9点整。jd_live_redrian.js拿到的
![DC15C3AB-6C3F-48A9-A023-2427D283FC43](https://user-images.githubusercontent.com/83346323/118382170-4570d600-b625-11eb-99e9-2cda7bb7026f.jpeg)
