### ISSUE TITLE
京东健康社区收集健康能量

### ISSUE THREAD

**Issue by dnxbice** [wisz2021/jd_docker#173]
昨晚还没问题 今早开始报错了
![QQ截图20210514100521](https://user-images.githubusercontent.com/24774919/118209885-1549fb80-b49c-11eb-9037-7c65d1827d72.png)

**Comment by kusiru** [comment]
更新node

**Comment by BlueSpiderGIGI** [comment]
> 昨晚还没问题 今早开始报错了
> ![QQ截图20210514100521](https://user-images.githubusercontent.com/24774919/118209885-1549fb80-b49c-11eb-9037-7c65d1827d72.png)

[https://github.com/wisz2021/jd_docker/issues/161](url)
