### ISSUE TITLE
使用自定义任务覆盖默认任务后日志无法正常写入了

### ISSUE THREAD

**Issue by dnxbice** [wisz2021/jd_docker#178]
使用自定义任务覆盖默认任务后日志无法正常写入了会显示/bin/ash redir error错误 但是脚本是在执行的 投送的通知也可以收到 如果手动执行脚本日志是可以生成的 请问大神如何解决

**Comment by lockingxp** [comment]
自定义任务那个文件有问题
你用了win的换行符
换成unix的

**Comment by dnxbice** [comment]
> 自定义任务那个文件有问题
> 你用了win的换行符
> 换成unix的

谢谢大神
