### ISSUE TITLE
京喜工厂脚本执行报错，有哪位大佬能告知一下怎么解决吗

### ISSUE THREAD

**Issue by Maccrack** [wisz2021/jd_docker#179]
❗️京喜工厂, 错误!
May 14 16:50:08 TypeError: Cannot destructure property 'componentList' of 'GetUserComponentRes.data' as it is undefined.
May 14 16:50:08     at PickUp (/scripts/jd_dreamFactory.js:741:13)
May 14 16:50:08     at processTicksAndRejections (internal/process/task_queues.js:93:5)
May 14 16:50:08     at async jdDreamFactory (/scripts/jd_dreamFactory.js:144:5)
May 14 16:50:08     at async /scripts/jd_dreamFactory.js:95:7

**Comment by dongjun613** [comment]
一样的错误，更新容器也没用，无法开团了

**Comment by 275244143** [comment]
一样错误～

**Comment by wisz2021** [comment]
已修复
