### ISSUE TITLE
[求助] 请问下有没有大佬知道这些京豆怎么拿得到，看了京豆获取记录并没有啊

### ISSUE THREAD

**Issue by smzcs** [wisz2021/jd_docker#184]
![693A510A-A6DA-4D83-B948-A15AF9ED86E7](https://user-images.githubusercontent.com/10540916/118343356-1726c400-b55b-11eb-9318-94a2e88609bb.jpeg)

**Comment by jinpin** [comment]
重复打印而已，5858其实就是58

**Comment by yeng000** [comment]
小bug，打了两遍

**Comment by wisz2021** [comment]
是的。
