### ISSUE TITLE
关于yml中参数设定问题

### ISSUE THREAD

**Issue by underlaw** [wisz2021/jd_docker#187]
我把yml文件中的CASH_EXCHANGE=true参数等设置好,重启docker，用/env命令查看，比如CASH_EXCHANGE=true这 个就没有，JD_JOY_REWARD_NAME yml文件设为500，用/env命令查看为20。

请问参数在yml里设置好了，安装后/env查看有些丢失，有些不是按自己设定是，是因为什么了

**Comment by lockingxp** [comment]
重启这一步是从哪学的

**Comment by underlaw** [comment]
> 重启这一步是从哪学的

up -d吗

**Comment by underlaw** [comment]
ok了谢谢
