### ISSUE TITLE
每次容器重启，都要重新升级node，不然健康社区就会报错

### ISSUE THREAD

**Issue by TGhoul** [wisz2021/jd_docker#188]
每次容器重启都需要执行 apk add nodejs-current 命令升级 node，请问大佬为什么不做到容器里面呢？

**Comment by MrQcc** [comment]
> 每次容器重启都需要执行 apk add nodejs-current 命令升级 node，请问大佬为什么不做到容器里面呢？

是不是报SyntaxError: Unexpected token '.'  
是进入到容器里再执行升级吗

**Comment by wisz2021** [comment]
容器目前已经就是最新的node 版本呀。

**Comment by TGhoul** [comment]
> 容器目前已经就是最新的node 版本呀。

最新的是5.12版本吗？还是 latest 是最新版？

**Comment by TGhoul** [comment]
> 容器目前已经就是最新的node 版本呀。

Pulling jd_scripts (lxk0301/jd_scripts:)...
latest: Pulling from lxk0301/jd_scripts
339de151aab4: Pull complete
ba3d5975fa10: Pull complete
Digest: sha256:f4882af4e9a053cfe9bb9fc0066691e675106f0d5495c30c052b61ffc24de4f3
Status: Downloaded newer image for lxk0301/jd_scripts:latest

我这边拉取的 jd_scripts:latest 好像和 dockerhub 上 jd_scripts:latest 的 sha256 不一样，好奇怪

**Comment by yzliufujin** [comment]
启动时都会提示：
 ⚠️Docker镜像版本更新通知⚠️
升级容器内部node版本(v14.5.0)

**Comment by yzliufujin** [comment]
> 容器目前已经就是最新的node 版本呀。

 ⚠️Docker镜像版本更新通知⚠️

升级容器内部node版本(v14.5.0)

**Comment by wisz2021** [comment]
> > 容器目前已经就是最新的node 版本呀。
> 
> 最新的是5.12版本吗？还是 latest 是最新版？

其实是一个版本，  5.12  只是某些人想看版本号 。我新增的

**Comment by solar24** [comment]
我也是，刚才发现。重启就报错了 镜像160a62df5141

**Comment by lee-yuanchun** [comment]
> > 特卫队
> 
> 拉jd_scripts （lxk0301/jd_scripts：）...
> 最新： 从
> lxk0301/jd_scripts 339de151aab4 中拉取
> ： 拉完全 ba3d5975fa10： 拉完整
> 文摘： sha256：f4882af4e9a053cfe 9bb9fc0066691e675106f0d5495c30c052b61ffc24de4f3
> 状态：下载的 lxk0301/jd_scripts的最新图像
> 
> ・jd_scripts：最新一期《最新款》jd_scripts：最新一期《沙256》《共克时jd_scripts



> > 容器目前已经就是最新的node 版本呀。
> 
> Pulling jd_scripts (lxk0301/jd_scripts:)...
> latest: Pulling from lxk0301/jd_scripts
> 339de151aab4: Pull complete
> ba3d5975fa10: Pull complete
> Digest: sha256:f4882af4e9a053cfe9bb9fc0066691e675106f0d5495c30c052b61ffc24de4f3
> Status: Downloaded newer image for lxk0301/jd_scripts:latest
> 
> 我这边拉取的 jd_scripts:latest 好像和 dockerhub 上 jd_scripts:latest 的 sha256 不一样，好奇怪

我刚看了下  我也是这样子的，来回捣鼓了好久，把阿里云加速器下了，直接拉，指定官方仓库拉都是和docker hub上的不一样，蛋疼

**Comment by BlueSpiderGIGI** [comment]
> 容器目前已经就是最新的node 版本呀。

dockerhub拉去最新的镜像里面的NODE和NPM还真不是最新的，后来我都是全部安装完重新commit个新的镜像出来，要不每次都得重启后要下载

**Comment by TGhoul** [comment]
> > 容器目前已经就是最新的node 版本呀。
> 
> dockerhub拉去最新的镜像里面的NODE和NPM还真不是最新的，后来我都是全部安装完重新commit个新的镜像出来，要不每次都得重启后要下载

确实是这样的，我直接拉的 5.12 版本 node 版本还是提示需要升级到最新版

**Comment by xiaokaixuan** [comment]
FROM 改回 `alpine:3.12`后node版本必然也会降回去。

**Comment by TGhoul** [comment]
> FROM 改回 `alpine:3.12`后node版本也会跟着降回去的。

是不是因为前两天 ARM 不兼容又改回来了？

**Comment by xiaokaixuan** [comment]
> > FROM 改回 `alpine:3.12`后node版本也会跟着降回去的。
> 
> 是不是因为前两天 ARM 不兼容又改回来了？

是的  我已经提了 PR #203

**Comment by xiaokaixuan** [comment]
镜像已经更新了 可以Close了

**Comment by TGhoul** [comment]
> 镜像已经更新了 可以Close了

好的，谢谢大佬
