### ISSUE TITLE
data?.data?.bizCode报错，请问这是什么语法？

### ISSUE THREAD

**Issue by nssiwi** [wisz2021/jd_docker#190]
` /scripts/jd_health_collect.js:79

if (data?.data?.bizCode === 0) {

^

SyntaxError: Unexpected token '.' `

我把这里的问号去掉后，还有报错

` /scripts/jd_health_collect.js:84

data.data.result.produceScore ?? "未知"

^

SyntaxError: Unexpected token '?' `

请问如何处理？

**Comment by lockingxp** [comment]
重新拉最新镜像 或者手动升级nodejs 去翻以前的issue

**Comment by nssiwi** [comment]
> 重新拉最新镜像 或者手动升级nodejs 去翻以前的issue

感谢，问题已解决
