### ISSUE TITLE
v4bot 萌宠任务总是出现错误,农场偶尔也会出现这个错误.

### ISSUE THREAD

**Issue by LonelyTriangle** [wisz2021/jd_docker#194]
![pet](https://user-images.githubusercontent.com/72370295/118395403-e6d74680-b67c-11eb-9b84-e3318182d7f1.png)

**Comment by wisz2021** [comment]
主要原因 你的网络异常 ，导致拿到的数据异常 ，

然后脚本判断不严谨 。 导致出错
