### ISSUE TITLE
通过浏览器获取Cookie的方式，某东好像修改了

### ISSUE THREAD

**Issue by sh1shan** [wisz2021/jd_docker#195]
今天想更新一下Cookie，通过谷歌浏览器获取的方式，试了好几回没找到log.gif,只有一个m?std=啥啥啥的，想问下各位大佬还有其他方式获取Cookie嘛？Cookie过期了

**Comment by limoruirui** [comment]
干嘛要找log.gif 直接搜pt_key 随便拿一个不就行了

**Comment by wisz2021** [comment]
我这边是有的， 不过你随便找一个  请求头的cookie， 都是有的


![image](https://user-images.githubusercontent.com/83346323/118424901-a8806c80-b6fa-11eb-89ef-df8e22c0e168.png)
