### ISSUE TITLE
惊喜农场有个账号一直报ret:147 retmsg:"filter"

### ISSUE THREAD

**Issue by rklhxyk1128** [wisz2021/jd_docker#198]
容器里放着4个账号，就是最后一个一直提示这个，没法自动做任务，只有每天的自动互助。 其他账号都没事，这种情况是我哪里操作错了吗？  是不是第四个账号需要在京东app上领惊喜的种子呀

**Comment by wisz2021** [comment]
算是脚本有点点问题， 然后导致此账号出现了问题。手动做任务应该是正常 。
