### ISSUE TITLE
赶快来反馈下，关于定时任务

### ISSUE THREAD

**Issue by underlaw** [wisz2021/jd_docker#2]
l大，各位大
docker环境

定时任务有什么快速生效的方法吗（除restart)

**Comment by qirenzhidao** [comment]
docker-compose up -d

**Comment by underlaw** [comment]
> docker-compose up -d

晕，这是快速吗，不是，这是重新安装

**Comment by dee-lii** [comment]
快速生效的意思是，立马执行一遍脚本吗？

**Comment by underlaw** [comment]
> 快速生效的意思是，立马执行一遍脚本吗？

不是啊，就是cron   改了，让他定时快速生效

**Comment by qirenzhidao** [comment]
> 
> 
> > 快速生效的意思是，立马执行一遍脚本吗？
> 
> 不是啊，就是cron 改了，让他定时快速生效

这个你直接改了，就是即时生效的吧

**Comment by underlaw** [comment]
> > > 快速生效的意思是，立马执行一遍脚本吗？
> > 
> > 
> > 不是啊，就是cron 改了，让他定时快速生效
> 
> 这个你直接改了，就是即时生效的吧

。。。。。不是

**Comment by tarianwei** [comment]
> > 快速生效的意思是，立马执行一遍脚本吗？
> 
> 不是啊，就是cron 改了，让他定时快速生效

直接输入crond回车 ,然后再观察一下。我也才发现没有cron 服务

**Comment by gitupdate** [comment]
没有。需要docker-conpose restart一下

**Comment by qq995764533** [comment]
我restart都不会立即生效 只能先stop 再up -d才能马上生效

**Comment by lockingxp** [comment]
手动运行一次docker/default_task.sh

**Comment by lddsb** [comment]
#4
