### ISSUE TITLE
TG用/env不显示变量值..............

### ISSUE THREAD

**Issue by gcbzq32l** [wisz2021/jd_docker#214]
5个JD号刚开始是可以正常显示的.....然后按教程里的用@和&隔开和朋友交换的互助码后...
可能由于太长了不显示了.请问是TG的原因还是就是太长不显示了??

**Comment by xinjang** [comment]
tg似乎经常掉线，重启docker看看

**Comment by wisz2021** [comment]
> 5个JD号刚开始是可以正常显示的.....然后按教程里的用@和&隔开和朋友交换的互助码后...
> 可能由于太长了不显示了.请问是TG的原因还是就是太长不显示了??

是的， 账号太多， 推送内容太多，会导致推送失败
