### ISSUE TITLE
京东农场互助码交换

### ISSUE THREAD

**Issue by xdj86** [wisz2021/jd_docker#216]
京东农场互助码交换有没有来的，互助啊。

**Comment by 275244143** [comment]
互助tg群：https://t.me/joinchat/mCOj39a2JU5jMTZl

**Comment by xdj86** [comment]
这是我的互助码 如果给我助力了 请@我 发上您的互助码，我将给你助力。
京东农场】c9ca58b253fe4ca981cebb20844e2e38
京东萌宠】MTE0MDkyMjEwMDAwMDAwNDc5NjQ1Mzc=
种豆得豆】gaq4q3asomfbux46a7rnagd7yy
东东工厂】T0079qkpSBgCjVWnYaS5kRrbA

**Comment by 9k001** [comment]
这里是提issues的地方
你们这么搞是闹啥
