### ISSUE TITLE
京东农场助力码问题 v4-bot

### ISSUE THREAD

**Issue by xdj86** [wisz2021/jd_docker#228]
我用的v4-bot，互助码填写如下：

## ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ 第三区域：互助码填写区域 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

 MyFruit1="c9ca58b253fe4ca981cebb20844e2e38"  # 这是Cookie1这个账号的互助码
 MyFruitA="7665ea0a454743219b84c742fcb1744e"  # 这是我和别人交换互助，另外一个用户A的互助码
 MyFruitB="71f8f6ff41434d2e94b2acf8ac4a5ea8"  # 这是我和别人交换互助，另外一个用户B的互助码
 MyFruitC="7432eebb63774a69aba7a818058ec576h"  # 这是我和别人交换互助，另外一个用户C的互助码

运行jd_fruit  log显示：
由于您环境变量(FRUITSHARECODES)里面未提供助力码，故此处运行将会给脚本内置的码进行助力，请知晓！
共1个京东账号
您提供了2个账号的农场助力码
开始【京东账号1】xdj86

随机取个20码放到您固定的互助码后面(不影响已有固定互助)
第1个京东账号将要助力的好友["0a74407df5df4fa99672a037eec61f7e","dbb21614667246fabcfd9685b6f448f3","6fbd26cc27ac44d6a7fed34092453f77","61ff5c624949454aa88561f2cd721bf6","56db8e7bc5874668ba7d5195230d067a","1732254b62d5453fbfb47ad837a44ee1","5da27cd6b28c408cbdc079c615cf1204","da7678e67c3c4b5ba713417bd1ee13b2","8607c5d9ebcf4db4a00615b2a8227c16","2f978fdf28f14ee29175efe6d3de56f2","cc1b02151063496d8d60a2665330f04e","0a99abe6a6be4e6d96ccaa62e787a192","4ac88e2f97ad44f681d5e34afe13f119","fff30b766ec241e28fdee14626ea79d1","ae8aee1c42184b4985dfb94a72c62f33","198a1424ecec4f819f9500e12ab8d1fe","ee5a305aeddb49c7b71121eabaf01b0f","42c754e3fbec4432a1a13b57c0963e65","3f4b2b6ca5994800a5423f5ca655fbb4","c331d2fef7154c5aa61f729f0bf781b4","e1deb4fe7f7043b78b8f19165fbbf7fa","3076264c497b412a8b9346d56b54cc01","4b18821aa98e42328eb21d37cfcd8e7b","e907cafc669847d3a432f4f96076d8aa","5dd913c398244d668042c1cdbd5fdcf7"]

竟然不优先给固定互助  MyFruitA  MyFruitB  MyFruitC助力 给随机号码助力了。
这不科学啊。

**Comment by xdj86** [comment]
请问这个 FRUITSHARECODES在哪设置哦

**Comment by lockingxp** [comment]
问错地方了 去你用的项目问
怀疑是你写的不对 是不是不应该有双引号
