### ISSUE TITLE
京喜工厂开团参团失败

### ISSUE THREAD

**Issue by ranheqiao** [wisz2021/jd_docker#237]
今天新的10万电力活动一直开团参团失败

**Comment by ranheqiao** [comment]
<img width="412" alt="a9d9d2b7895da00b3e027e72d590464" src="https://user-images.githubusercontent.com/43024843/118904688-f55b8180-b94c-11eb-9203-cd4774de09ab.png">
<img width="395" alt="44026672e094b6044dff1520153c6ba" src="https://user-images.githubusercontent.com/43024843/118904696-f8567200-b94c-11eb-8a0d-aeb9fc87dccf.png">

**Comment by dongjun613** [comment]
自己抓包获取activeId

**Comment by ryan016** [comment]
> 自己抓包获取activeId

然后填列在哪呢？谢谢！

**Comment by X-Mars** [comment]
```
投入失败，电力不足，快去做任务吧~

团活动ID  mNGPTrOPluOSeZcupPI40w==
团ID  KzSuxbb7vVSe1Smajts1Ug==

今日剩余开团次数：3次
之前的团已过期，准备重新开团

开团异常：{"msg":"活动已结束，请稍后再试~","nowTime":1621478613,"ret":10218}

开团情况:1/6


此团未达领取团奖励人数：6人

5/19/2021, 2:50:09 PM参加团主【r_QxrFc5bueBNuGNEteZPA==】失败
5/19/2021, 3:55:06 PM参加团主【xt*lyk】的奖励已经领取成功
5/19/2021, 1:52:33 AM参加团主【r_QxrFc5bueBNuGNEteZPA==】失败
5/18/2021, 12:52:45 PM参加团主【r_QxrFc5bueBNuGNEteZPA==】失败
5/18/2021, 12:50:30 AM参加团主【r_QxrFc5bueBNuGNEteZPA==】失败
5/17/2021, 11:50:32 AM参加团主【r_QxrFc5bueBNuGNEteZPA==】失败
5/16/2021, 10:50:48 PM参加团主【r_QxrFc5bueBNuGNEteZPA==】失败
5/16/2021, 9:50:15 AM参加团主【r_QxrFc5bueBNuGNEteZPA==】失败
5/14/2021, 12:50:45 PM参加团主【r_QxrFc5bueBNuGNEteZPA==】失败
5/14/2021, 12:03:18 AM参加团主【r_QxrFc5bueBNuGNEteZPA==】失败
```

俺也一样

**Comment by ElsaKing** [comment]
哪位大佬可以分享下今天工厂参团的activeid吗 谢谢

**Comment by piaoyun** [comment]
> 自己抓包获取activeId

大佬。请问下，关键字搜索什么呢？谢谢

**Comment by ranheqiao** [comment]
> 自己抓包获取activeId

请问大佬有什么比较简便的抓包activeid的方法吗

**Comment by dongjun613** [comment]
> > 自己抓包获取activeId
> 
> 然后填列在哪呢？谢谢！

脚本里有个变量，说太明白了涉及修改作者脚本了。

**Comment by dongjun613** [comment]
> > 自己抓包获取activeId
> 
> 请问大佬有什么比较简便的抓包activeid的方法吗

使用fiddler工具进行手机app抓包

**Comment by dongjun613** [comment]
> > 自己抓包获取activeId
> 
> 大佬。请问下，关键字搜索什么呢？谢谢

关键字就是activeId

**Comment by ro9963** [comment]
最简单的方法，在网页打开京喜工厂，开F12，然后点开组团那里，抓到的应该就是activeId了
![image](https://user-images.githubusercontent.com/49099182/118938539-5ac96580-b981-11eb-8431-2346a9535e05.png)

**Comment by ro9963** [comment]
> > > > > 自己抓包获取activeId
> > > > 
> > > > 
> > > > 请问大佬有什么比较简便的抓包activeid的方法吗
> > > 
> > > 
> > > 使用fiddler工具进行手机app抓包
> > 
> > 
> > 抓了半天没抓到，大佬可以分享一下团活动id吗-。-
> 
> XBYi-5lVdNspWhlNwhpE6Q==

我加到jd_dreamfactory.js里面了，但是好像没生效，重启docker看到的log也还是原来的activeId。还需要改什么吗

**Comment by dongjun613** [comment]
> > > > > > 自己抓包获取activeId
> > > > > 
> > > > > 
> > > > > 请问大佬有什么比较简便的抓包activeid的方法吗
> > > > 
> > > > 
> > > > 使用fiddler工具进行手机app抓包
> > > 
> > > 
> > > 抓了半天没抓到，大佬可以分享一下团活动id吗-。-
> > 
> > 
> > XBYi-5lVdNspWhlNwhpE6Q==
> 
> 我加到jd_dreamfactory.js里面了，但是好像没生效，重启docker看到的log也还是原来的activeId。还需要改什么吗

requireConfig()方法里的团id重新赋值就行了

**Comment by ranheqiao** [comment]
> > > > > > > 自己抓包获取activeId
> > > > > > 
> > > > > > 
> > > > > > 请问大佬有什么比较简便的抓包activeid的方法吗
> > > > > 
> > > > > 
> > > > > 使用fiddler工具进行手机app抓包
> > > > 
> > > > 
> > > > 抓了半天没抓到，大佬可以分享一下团活动id吗-。-
> > > 
> > > 
> > > XBYi-5lVdNspWhlNwhpE6Q==
> > 
> > 
> > 我加到jd_dreamfactory.js里面了，但是好像没生效，重启docker看到的log也还是原来的activeId。还需要改什么吗
> 
> requireConfig()方法里的团id重新赋值就行了
> ![image](https://user-images.githubusercontent.com/13210762/118942450-4f783900-b985-11eb-92cd-3921e9b8ae38.png)
> 今天运行完记得还原回去。

感谢大佬

**Comment by piaoyun** [comment]
> 最简单的方法，在网页打开京喜工厂，开F12，然后点开组团那里，抓到的应该就是activeId了
> ![image](https://user-images.githubusercontent.com/49099182/118938539-5ac96580-b981-11eb-8431-2346a9535e05.png)

网页是访问那个地址登陆呢。谢谢
