### ISSUE TITLE
跳跳乐瓜分京豆,无法跳过障碍

### ISSUE THREAD

**Issue by cjh19831115** [wisz2021/jd_docker#239]
日志：执行骰子任务
丢骰子
丢骰子结果：boom
执行骰子任务
丢骰子
丢骰子结果：boom
执行骰子任务
丢骰子
丢骰子结果：boom
执行骰子任务
丢骰子
丢骰子结果：boom
执行骰子任务
丢骰子
丢骰子结果：boom
执行骰子任务
丢骰子
丢骰子结果：boom
执行骰子任务
丢骰子
丢骰子结果：boom
执行骰子任务
丢骰子
丢骰子结果：boom

**Comment by bontheway** [comment]
死循环了

**Comment by wisz2021** [comment]
已修复
