### ISSUE TITLE
今天提示cookie失效，更新cookie后脚本也能正常运行，但是微信推送仍一直推送提示脚本cookie失效，是什么问题呢？

### ISSUE THREAD

**Issue by maple-spirit** [wisz2021/jd_docker#258]

**Comment by piaoyun** [comment]
进程找到，kill然后，重新跑。因为失效的ck已经在跑着了。

**Comment by lockingxp** [comment]
提问的时候说清楚 写在yml环境变量里还是在cookieslist

**Comment by maple-spirit** [comment]
> 进程找到，kill然后，重新跑。因为失效的ck已经在跑着了。

不行，删了容器镜像，重新跑也是一样….

**Comment by lockingxp** [comment]
在哪更新的  yml 还是cookieslist 还是两个地方都有

**Comment by maple-spirit** [comment]
> 在哪更新的 yml 还是cookieslist 还是两个地方都有

是在yml更新cookie

**Comment by gebaolei** [comment]
如果使用了spnode，要更新cookie.list

**Comment by maple-spirit** [comment]
> 如果使用了spnode，要更新cookie.list
嗯是这个原因，更新这个cookie.list就好了，谢谢

**Comment by BLEACHman123** [comment]
> > 如果使用了spnode，要更新cookie.list
> > 嗯是这个原因，更新这个cookie.list就好了，谢谢

兄弟，我和你一样的情况，请问怎么解决？我的是威联通nas

**Comment by maple-spirit** [comment]
> > > 如果使用了spnode，要更新cookie.list
> > > 嗯是这个原因，更新这个cookie.list就好了，谢谢
> 
> 兄弟，我和你一样的情况，请问怎么解决？我的是威联通nas

就是上面说的要一起更新cookie. list里的cookie

**Comment by BLEACHman123** [comment]
> > > > 如果使用了spnode，要更新cookie.list
> > > > 嗯是这个原因，更新这个cookie.list就好了，谢谢
> > 
> > 
> > 兄弟，我和你一样的情况，请问怎么解决？我的是威联通nas
> 
> 就是上面说的要一起更新cookie. list里的cookie

不知道怎么更新cookie. list，请指教

**Comment by maple-spirit** [comment]
> > > > > 如果使用了spnode，要更新cookie.list
> > > > > 嗯是这个原因，更新这个cookie.list就好了，谢谢
> > > 
> > > 
> > > 兄弟，我和你一样的情况，请问怎么解决？我的是威联通nas
> > 
> > 
> > 就是上面说的要一起更新cookie. list里的cookie
> 
> 不知道怎么更新cookie. list，请指教

在logs里有个cookie.lis，打开改就行了

**Comment by BLEACHman123** [comment]
> > > > > > 如果使用了spnode，要更新cookie.list
> > > > > > 嗯是这个原因，更新这个cookie.list就好了，谢谢
> > > > 
> > > > 
> > > > 兄弟，我和你一样的情况，请问怎么解决？我的是威联通nas
> > > 
> > > 
> > > 就是上面说的要一起更新cookie. list里的cookie
> > 
> > 
> > 不知道怎么更新cookie. list，请指教
> 
> 在logs里有个cookie.lis，打开改就行了

奇怪就是在这里了，我logs的文件夹里面没有cookie。lis这个文件
