### ISSUE TITLE
来客有礼“发现”tab，点了N次，还是无法获取token

### ISSUE THREAD

**Issue by ryan016** [wisz2021/jd_docker#26]
```
宠汪汪赛跑
【提示】来客有礼token失效，请重新获取
iOS用户微信搜索'来客有礼'小程序
点击底部的'发现'Tab
即可获取Token
```

**Comment by wisz2021** [comment]
iOS用的

**Comment by ryan016** [comment]
> iOS用的

那docker上跑脚本的该如何获取token呢？

**Comment by ryan016** [comment]
> > > iOS用的
> > 
> > 
> > 那docker上跑脚本的该如何获取token呢？
> > 昨天之前还一直好好的，就算提示失效，在微信小程序里点击“发现”tab就可以了，但今早开始就不管用了。
> 
> token 两个小时的有效期。如果需要。非iOS需自己抓包

抓包后获取的token要如何运用到docker中呢？谢谢！

**Comment by wisz2021** [comment]
> > > > iOS用的
> > > 
> > > 
> > > 那docker上跑脚本的该如何获取token呢？
> > > 昨天之前还一直好好的，就算提示失效，在微信小程序里点击“发现”tab就可以了，但今早开始就不管用了。
> > 
> > 
> > token 两个小时的有效期。如果需要。非iOS需自己抓包
> 
> 抓包后获取的token要如何运用到docker中呢？谢谢！

使用此环境变量吧

JOY_RUN_TOKEN


默认是拿大家上传到服务器的token

**Comment by ryan016** [comment]
> JOY_RUN_TOKEN

谢谢！！！！
