### ISSUE TITLE
关于 jd_syj 的助力问题

### ISSUE THREAD

**Issue by lonercci** [wisz2021/jd_docker#265]
老大能不能把jd_syj的内部助力分下组，活动好像可以开四次团，但是十几个号每天运行只能开一个团是什么情况，或者说我应该怎么设置呢

**Comment by limoruirui** [comment]
脚本可以开四次 只是一次过的时候就已经没有助力次数了

**Comment by limoruirui** [comment]
后面三次都是没助力次数的

**Comment by limoruirui** [comment]
给你个思路 第一次运行 容器只留5个号 运行之后改回来 然后第二次运行留前面的5个号加上4个新的 …… 这样就行

**Comment by lonercci** [comment]
> 给你个思路 第一次运行 容器只留5个号 运行之后改回来 然后第二次运行留前面的5个号加上4个新的 …… 这样就行

额，感觉这样手动好麻烦，代码运行的时候我基本都睡了，，，能不能从代码层面或者是写个另外脚本，（笑哭）

**Comment by limoruirui** [comment]
> > 给你个思路 第一次运行 容器只留5个号 运行之后改回来 然后第二次运行留前面的5个号加上4个新的 …… 这样就行
> 
> 额，感觉这样手动好麻烦，代码运行的时候我基本都睡了，，，能不能从代码层面或者是写个另外脚本，（笑哭）

思路给你了 不就是让你自己写个shell脚本搞定的事情么 定时运行定时改不就好了 干嘛要手动

**Comment by lonercci** [comment]
> > > 给你个思路 第一次运行 容器只留5个号 运行之后改回来 然后第二次运行留前面的5个号加上4个新的 …… 这样就行
> > 
> > 
> > 额，感觉这样手动好麻烦，代码运行的时候我基本都睡了，，，能不能从代码层面或者是写个另外脚本，（笑哭）
> 
> 思路给你了 不就是让你自己写个shell脚本搞定的事情么 定时运行定时改不就好了 干嘛要手动

明白了，感谢老哥
