### ISSUE TITLE
群晖docker日志提示utf-8-validate@^5.0.2 需要手工安装，不知道怎么操作？

### ISSUE THREAD

**Issue by backdreamliu** [wisz2021/jd_docker#274]
看到启动日志里面提到这么一句，不知道如何安装啊？谢谢！

npm WARN ws@7.4.5 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

**Comment by lockingxp** [comment]
一直都有 忽略即可

**Comment by backdreamliu** [comment]
谢谢回复，也不知道有啥影响...

**Comment by backdreamliu** [comment]
在网上找了下教程，解决了，重启没有这个提示啦。

方法：
1.在“容器-详情-终端机”里面新增bash。
2.在bash里面输入命令行
`npm install utf-8-validate --save-optional`
3.重启容器，发现提示消失了:D
