### ISSUE TITLE
docker_entrypoint.sh报错

### ISSUE THREAD

**Issue by dnxbice** [wisz2021/jd_docker#275]
如图所示 最近几天总出现这个连接错误的通知 但是手动执行是可以的 请问是哪里出了问题？
<img width="866" alt="屏幕截图 2021-05-24 093313" src="https://user-images.githubusercontent.com/24774919/119285249-34067a00-bc74-11eb-9929-07101c25c31c.png">

**Comment by lockingxp** [comment]
字面意思
同时连接数不能超过5个
手动也可能遇到

**Comment by dnxbice** [comment]
懂了
