### ISSUE TITLE
美丽研究院 报错

### ISSUE THREAD

**Issue by parakai** [wisz2021/jd_docker#281]
麻烦大佬看一下
开始任务：""to_exchange"
(node:17353) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'coins' of undefined
    at WebSocket.client.onmessage (/scripts/jd_beauty.js:500:36)
(node:17353) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by WinterBoring** [comment]
同样报错！
