### ISSUE TITLE
城市分现金不能先助力自己的码再去给陌生人助力？

### ISSUE THREAD

**Issue by hdstar2009** [wisz2021/jd_docker#282]
除了优先给作者两个码助力以外，是否应该优先给CITY_SHARECODES设置的码助力？
助力完后次数还有剩余再给陌生人助力。
应该是这样比较合理吧。现在是自己的码设置在CITY_SHARECODES里面了，自己其他账号明明满3次助力机会但是就不给自己的码助力而去给陌生人一次助力完3次。这样我只能先把jd_city.js脚本删了。
是我理解错误还是jd_city.js脚本还没完善（今天刚出活动）？

**Comment by hdstar2009** [comment]
不然的话自己的码提交不到bot助力码池里面，自己其他号的次数又都给网友助力了，自己的号就都歇菜了啊。

**Comment by xdj86** [comment]
事实上好像是这样 环境变量还没更新 不知道分现金能分多少哦

**Comment by fengmikaelson** [comment]
脚本自带的助力好像不止2个?我看log有十几个。

**Comment by hdstar2009** [comment]
> 脚本自带的助力好像不止2个?我看log有十几个。

固定好像是作者的两个，然后就是从网络下载的，现金这个目前是2000多人的池了

**Comment by fengmikaelson** [comment]
> > 脚本自带的助力好像不止2个?我看log有十几个。
> 
> 固定好像是作者的两个，然后就是从网络下载的，现金这个目前是2000多人的池了

蛋疼呀，今天的助力机会全给陌生人了T-T

**Comment by lostme01** [comment]
城城分现金好像不支持 容器内账号互助，如果不手动设置助力码就会给 陌生人助力

**Comment by google-mirror** [comment]
自己助力也没几毛钱, 躺平

**Comment by limoruirui** [comment]
> 自己助力也没几毛钱, 躺平

第一次还是挺多的 后面就没了

**Comment by hdstar2009** [comment]
可以了。多个账户内部互助写法应该是 A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D  
A B C D是你的sharecode，10个账号就按上面写10组，更多账号继续

**Comment by luoxixi-sophia** [comment]
A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D
请问这个应该填在哪啊？sharecode.log里面会更新啊

**Comment by fengmikaelson** [comment]
> A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D
> 请问这个应该填在哪啊？sharecode.log里面会更新啊

sharecode里虽然有更新，但是自动互助好像没有采用

**Comment by luoxixi-sophia** [comment]
> > A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D
> > 请问这个应该填在哪啊？sharecode.log里面会更新啊
> 
> sharecode里虽然有更新，但是自动互助好像没有采用

嗯，我查看城城的log里面会获取城城领现金的配置文件，就是没找到这个配置文件究竟在哪，sharecode的确没采用，很蛋疼

**Comment by luoxixi-sophia** [comment]
> > > A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D
> > > 请问这个应该填在哪啊？sharecode.log里面会更新啊
> > 
> > 
> > sharecode里虽然有更新，但是自动互助好像没有采用
> 
> 嗯，我查看城城的log里面会获取城城领现金的配置文件，就是没找到这个配置文件究竟在哪，sharecode的确没采用，很蛋疼

应该是要在环境变量里设置给CITY_SHARECODES

**Comment by fengmikaelson** [comment]
> > > > A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D
> > > > 请问这个应该填在哪啊？sharecode.log里面会更新啊
> > > 
> > > 
> > > sharecode里虽然有更新，但是自动互助好像没有采用
> > 
> > 
> > 嗯，我查看城城的log里面会获取城城领现金的配置文件，就是没找到这个配置文件究竟在哪，sharecode的确没采用，很蛋疼
> 
> 应该是要在环境变量里设置给CITY_SHARECODES

自己加环境变量
CITY_SHARECODES=A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D&A@B@C@D
