### ISSUE TITLE
ENABLE_AUTO_HELP 环境变量似乎无效

### ISSUE THREAD

**Issue by qianxu2001** [wisz2021/jd_docker#291]
如题，我设置为了 true，但是在任务执行时依旧会助力陌生人，而不是我自己的账户，我一个容器内配置了四个账户

**Comment by taklele** [comment]
> 如题，我设置为了 true，但是在任务执行时依旧会助力陌生人，而不是我自己的账户，我一个容器内配置了四个账户

我开启了之后，有的活动是可以互相助理的，有的活动不行，比如最新的城城分现金就不可以，

**Comment by qianxu2001** [comment]
乱
