### ISSUE TITLE
口袋书店和签到领现金问题

### ISSUE THREAD

**Issue by crazyzzcc** [wisz2021/jd_docker#295]
1.京东账号1尚未开启口袋书店，请手动开启。这个在哪里开启？
2.签到领现金好友互助码：没有助力码，不导出。这个互助码在jd_cash.log里没有，应该在哪里获取？

**Comment by MapleStoryXiaoA** [comment]
1. 首页 频道 京东图书
2. 不知道

**Comment by crazyzzcc** [comment]
> 1. 首页 频道 京东图书
> 2. 不知道

你好，第一条京东图书进去了，但是没有找到呀，可以具体一些吗

**Comment by winsphinx** [comment]
> > 1. 首页 频道 京东图书
> > 2. 不知道
> 
> 你好，第一条京东图书进去了，但是没有找到呀，可以具体一些吗

进去右上角，“签” 图标
进去后下方“每日参加活动”

**Comment by lockingxp** [comment]
以前签到领现金有邀请助力，那时候有助力码
后来这个助力取消了，现在是弄不到助力码的

**Comment by crazyzzcc** [comment]
> > > 1. 首页 频道 京东图书
> > > 2. 不知道
> > 
> > 
> > 你好，第一条京东图书进去了，但是没有找到呀，可以具体一些吗
> 
> 进去右上角，“签” 图标
> 进去后下方“每日参加活动”

谢谢大佬！

**Comment by crazyzzcc** [comment]
> 以前签到领现金有邀请助力，那时候有助力码
> 后来这个助力取消了，现在是弄不到助力码的

谢谢大佬！
