### ISSUE TITLE
【已解决】命令追加到默认命令后出现问题

### ISSUE THREAD

**Issue by di7gan** [wisz2021/jd_docker#296]
在文件：docker-compose.yml 中添加如下字段
`      - CUSTOM_LIST_FILE=https://gitee.com/马赛克/crontab/raw/master/crontab.sh`
进入docker容器，使用 crontab -l 命令，看到了上述网址中的命令。
我的设置如下
`*/15 * * * * node /scripts/马赛克.js |ts >> /scripts/logs/马赛克.log 2>&1`

注意：我使用上述命令手动执行，能够产生日志。
问题：我设置的这条命令没有运行，因为没有产生上述的日志文件。
请问我的问题出在那里

**Comment by nomoneynolife** [comment]
低级错误！

大哥你确定你的脚本文件已经下载了？

**Comment by lockingxp** [comment]
引用的远程任务列表 是别人的还是你自己写的
你下载下来看一下 里面是不是用了win的换行符

**Comment by di7gan** [comment]
> 低级错误！
> 
> 大哥你确定你的脚本文件已经下载了？

文件利用宿主传递到了docker里面，不然手动运行不会成功

**Comment by di7gan** [comment]
> 引用的远程任务列表 是别人的还是你自己写的
> 你下载下来看一下 里面是不是用了win的换行符

我自己写的，我尝试上传大佬们的sh文件在去改一下试试

**Comment by di7gan** [comment]
> 在文件：docker-compose.yml 中添加如下字段
> ` - CUSTOM_LIST_FILE=https://gitee.com/马赛克/crontab/raw/master/crontab.sh`
> 进入docker容器，使用 crontab -l 命令，看到了上述网址中的命令。
> 我的设置如下
> `*/15 * * * * node /scripts/马赛克.js |ts >> /scripts/logs/马赛克.log 2>&1`
> 
> 注意：我使用上述命令手动执行，能够产生日志。
> 问题：我设置的这条命令没有运行，因为没有产生上述的日志文件。
> 请问我的问题出在那里
