### ISSUE TITLE
能豆实现更新Cookie不重启容器

### ISSUE THREAD

**Issue by hys578084** [wisz2021/jd_docker#3]
每次cookie失效以后都要docker-compose up -d来重启容器，重启之后node版本又要重新升级，比较麻烦。建议将cookie存放在一个文件里，然后和logs文件夹一样挂载到容器中，每次更新cookie时只需要修改文件内容即可。这样不需要重启容器，cookie更新也及时。

**Comment by haohaoget** [comment]
可以啊，直接在cookie.list里面修改就是了

**Comment by hys578084** [comment]
> 可以啊，直接在cookie.list里面修改就是了

docker容器里面没有这个文件吧？node版本是使用的jdCookie.js这个文件，但是修改这个文件的话git pull又会被覆盖掉，而且自动助力就不起作用了。

**Comment by Sooongz** [comment]
> > 可以啊，直接在cookie.list里面修改就是了
> 
> docker容器里面没有这个文件吧？node版本是使用的jdCookie.js这个文件，但是修改这个文件的话git pull又会被覆盖掉，而且自动助力就不起作用了。

在logs里

**Comment by cxaa21** [comment]
cookie.list 是开启了bot功能才能用的吧 默认是不行的
