### ISSUE TITLE
根据教程 输入docker-compose up -d.然后就一堆看不懂的出来了

### ISSUE THREAD

**Issue by huangxinwanl** [wisz2021/jd_docker#301]
![image](https://user-images.githubusercontent.com/78459308/119538716-f6156d00-bdbd-11eb-8b17-7f3413f9f0b8.png)
![image](https://user-images.githubusercontent.com/78459308/119538783-07f71000-bdbe-11eb-976e-ac85d63b8a92.png)
![image](https://user-images.githubusercontent.com/78459308/119538850-1a714980-bdbe-11eb-9fba-bed18fda99b3.png)
不知道哪步出了问题。

**Comment by huangxinwanl** [comment]
![image](https://user-images.githubusercontent.com/78459308/119540309-e434c980-bdbf-11eb-9bbb-daedea178ab9.png)
已经安装好了docker-compose

**Comment by lockingxp** [comment]
sudo

**Comment by huangxinwanl** [comment]
> sudo

用了的。还是一样。

**Comment by dnxbice** [comment]
> ![image](https://user-images.githubusercontent.com/78459308/119538716-f6156d00-bdbd-11eb-8b17-7f3413f9f0b8.png)
> ![image](https://user-images.githubusercontent.com/78459308/119538783-07f71000-bdbe-11eb-976e-ac85d63b8a92.png)
> ![image](https://user-images.githubusercontent.com/78459308/119538850-1a714980-bdbe-11eb-9fba-bed18fda99b3.png)
> 不知道哪步出了问题。

之前也遇到了这个问题 常规方法没解决 重装了UBUNTU重新部署才OK

**Comment by Xiderowg** [comment]
docker确认装好了吗？`docker -v`看下是啥版本

**Comment by limoruirui** [comment]
建议重装系统 然后去docker官网装 不要直接用这边的命令

**Comment by qianxu2001** [comment]
不熟悉 wsl 就不要用，用虚拟机

**Comment by huangxinwanl** [comment]
> 不熟悉 wsl 就不要用，用虚拟机

虚拟机我也不熟。请问一下这个问题出在哪儿了呢？

**Comment by huangxinwanl** [comment]
> 建议重装系统 然后去docker官网装 不要直接用这边的命令

请问一下是重装了docker 然后再装docker-compose么？

**Comment by huangxinwanl** [comment]
> docker确认装好了吗？`docker -v`看下是啥版本

![image](https://user-images.githubusercontent.com/78459308/119617822-c6557c00-be34-11eb-8f7d-293ef104dfc0.png)

**Comment by limoruirui** [comment]
> > 建议重装系统 然后去docker官网装 不要直接用这边的命令
> 
> 请问一下是重装了docker 然后再装docker-compose么？

我是新系统 在官网先装docker 然后再装docker-compose

**Comment by Xiderowg** [comment]
> > docker确认装好了吗？`docker -v`看下是啥版本
> 
> ![image](https://user-images.githubusercontent.com/78459308/119617822-c6557c00-be34-11eb-8f7d-293ef104dfc0.png)

`systemctl status docker` 看下docker是否在运行，不在运行的话`systemctl enable docker & systemctl start docker`

**Comment by huangxinwanl** [comment]
> > > 建议重装系统 然后去docker官网装 不要直接用这边的命令
> > 
> > 
> > 请问一下是重装了docker 然后再装docker-compose么？
> 
> 我是新系统 在官网先装docker 然后再装docker-compos

>我试一下

**Comment by feijihong** [comment]
哥,你这个怎么解决的?
