### ISSUE TITLE
京喜农场无法读取内部配置的助力码

### ISSUE THREAD

**Issue by ranheqiao** [wisz2021/jd_docker#305]
这是之前的
<img width="446" alt="2cbbfd6db61e7e1048709d0314f4888" src="https://user-images.githubusercontent.com/43024843/119590415-5086eb80-be07-11eb-88d0-12c790ff1b90.png">
这是之后的
<img width="455" alt="4424dcfc354707fa0917809e3ba15ac" src="https://user-images.githubusercontent.com/43024843/119590427-55e43600-be07-11eb-896d-63337d95e6b3.png">

**Comment by scolyp** [comment]
+1
