### ISSUE TITLE
疯狂的JOY活动是不是取消了？

### ISSUE THREAD

**Issue by dnxbice** [wisz2021/jd_docker#322]
昨天开始JOY挂机总是显示系统错误 要么就是金币数 观看数获取失败 打开京东APP也找不到疯狂JOY的入口了 是不是这个活动取消了？

**Comment by fengmikaelson** [comment]
看了下日志还有在运行，但是入口确实没找到= =

**Comment by dnxbice** [comment]
> 看了下日志还有在运行，但是入口确实没找到= =

刚才又看了一下 近2小时 都是正常运行 但是APP还是没有入口

**Comment by xinshikong** [comment]
入口还有一个地方，可以在 我的-京豆-合成拿分红进入

**Comment by dnxbice** [comment]
> 入口还有一个地方，可以在 我的-京豆-合成拿分红进入

谢谢指点 找到了 但是看日志还是时不时有错误的提示
