### ISSUE TITLE
拉取了镜像发现没有动物联盟脚本

### ISSUE THREAD

**Issue by limoruirui** [wisz2021/jd_docker#323]
Image ID 还是9f45bc0e865c 八天前的 执行过sudo docker-compose pull 但是没有拉取更新镜像的下载进度 直接就提示拉取完成 在tgbot上用git pull 提示 →→→ git -C /scripts/ pull 执行出错 ←←←

**Comment by beenewtree** [comment]
REPO-url用的哪个？

**Comment by limoruirui** [comment]
> REPO-url用的哪个？

git@gitee.com:lxk0301/jd_scripts.git
近期好像没看到说要改 一直用的这个

**Comment by dongjun613** [comment]
zoo.js

**Comment by limoruirui** [comment]
> zoo.js
没有

**Comment by fengmikaelson** [comment]
docker exec -it jd_scripts sh -c "docker_entrypoint.sh"

**Comment by limoruirui** [comment]
解决了 发现是因为前几天手机狂欢城活动又复活了 然后我拿了上一次活动的脚本挂载进去 没改名字 然后跟这次更新的冲突了 sudo docker-conpose pull居然没提示 用了sudo docker exec -it jd_scripts sh -c "git pull"才提示手机狂欢城脚本文件冲突
