### ISSUE TITLE
xmsports的token在env中如何设置添加

### ISSUE THREAD

**Issue by wushengtolearn** [wisz2021/jd_docker#33]
尝试了在环境中加入
- login_token=
- xmSportsToken=
都报错

**Comment by qq995764533** [comment]
目前还没有 可以找其它作者的

**Comment by wisz2021** [comment]
> 尝试了在环境中加入
> 
> * login_token=
> * xmSportsToken=
>   都报错

不好意思。可能是没写到文档上。

他的环境变量为：XM_SPORT_TOKEN
