### ISSUE TITLE
请教一下现在docker image和REPO_URL的配置

### ISSUE THREAD

**Issue by CfortWang** [wisz2021/jd_docker#331]
现在用的docker image是```registry.hub.docker.com/lxk0301/jd_scripts```，REPO_URL没有配置，能正常用，但是image ID跟置顶Issues的不一样，而且访问```registry.hub.docker.com/lxk0301/jd_scripts```已经404了，image ID正确的老哥能说一下你们的配置吗

**Comment by fengmikaelson** [comment]
![image](https://user-images.githubusercontent.com/10394327/119914338-7bea1180-bf92-11eb-8bdb-19ddd73f4ce2.png)

**Comment by fengmikaelson** [comment]
> ![image](https://user-images.githubusercontent.com/31876047/119915185-8c9b8700-bf94-11eb-9575-ea2f0834528a.png)
> 这是我的
> ![image](https://user-images.githubusercontent.com/31876047/119915276-bfde1600-bf94-11eb-916a-ff50f519e7f7.png)
> 这是置顶issue的，对不上

早更新过了啊。。。置顶的issue都20天以前了。

**Comment by CfortWang** [comment]
> > ![image](https://user-images.githubusercontent.com/31876047/119915185-8c9b8700-bf94-11eb-9575-ea2f0834528a.png)
> > 这是我的
> > ![image](https://user-images.githubusercontent.com/31876047/119915276-bfde1600-bf94-11eb-916a-ff50f519e7f7.png)
> > 这是置顶issue的，对不上
> 
> 早更新过了啊。。。置顶的issue都20天以前了。

我看之前的id也对不上= = 那我现在这个没问题吗

**Comment by fengmikaelson** [comment]
> > > ![image](https://user-images.githubusercontent.com/31876047/119915185-8c9b8700-bf94-11eb-9575-ea2f0834528a.png)
> > > 这是我的
> > > ![image](https://user-images.githubusercontent.com/31876047/119915276-bfde1600-bf94-11eb-916a-ff50f519e7f7.png)
> > > 这是置顶issue的，对不上
> > 
> > 
> > 早更新过了啊。。。置顶的issue都20天以前了。
> 
> 我看之前的id也对不上= = 那我现在这个没问题吗

就是9f45c这个。。。

**Comment by CfortWang** [comment]
> > > > ![image](https://user-images.githubusercontent.com/31876047/119915185-8c9b8700-bf94-11eb-9575-ea2f0834528a.png)
> > > > 这是我的
> > > > ![image](https://user-images.githubusercontent.com/31876047/119915276-bfde1600-bf94-11eb-916a-ff50f519e7f7.png)
> > > > 这是置顶issue的，对不上
> > > 
> > > 
> > > 早更新过了啊。。。置顶的issue都20天以前了。
> > 
> > 
> > 我看之前的id也对不上= = 那我现在这个没问题吗
> 
> 就是9f45c这个。。。你没看你的lastest跟我的是一样的吗

这个看到了，你上面那条我回复不了
