### ISSUE TITLE
做个人吧?填了城城助力参数还是帮别人助力???????

### ISSUE THREAD

**Issue by grey27** [wisz2021/jd_docker#333]
![image](https://user-images.githubusercontent.com/39294698/119924027-70ecac80-bfa5-11eb-9c00-cf02e2d9cfe4.png)
![image](https://user-images.githubusercontent.com/39294698/119924064-8235b900-bfa5-11eb-9046-965e7220bda4.png)

搁这当雷锋呢?

**Comment by adnimzby** [comment]
填的不对 1@2&1@2&1@2这样的格式填 有几个账号“1@2”就写几遍

**Comment by aliyy2021** [comment]
信求

**Comment by fengmikaelson** [comment]
你自己助力码格式没对啊。。。

**Comment by lockingxp** [comment]
做个人吧?好好看文档吧？

**Comment by Hyper-Beast** [comment]
看不懂说明建议删了别用了，这免费给别人打工怎么受得了，想到这都气的吃不下睡不着了

**Comment by yyetss** [comment]
*****。自己脑子不好使怪别人

**Comment by p5621571** [comment]
挺服的，就不能自己把auto_help.sh的参数改下？改完自动助力就生效了

**Comment by fengmikaelson** [comment]
> 挺服的，就不能自己把auto_help.sh的参数改下？改完自动助力就生效了

城城分现金没有自动助力吧？我记得不是要自己填的吗、

**Comment by p5621571** [comment]
> > 挺服的，就不能自己把auto_help.sh的参数改下？改完自动助力就生效了
> 
> 城城分现金没有自动助力吧？我记得不是要自己填的吗、

有啊，只是lxk把里面的参数写错了，你多看看其他的issues就知道了，脚本里面多写一句sed -i，就解决了

**Comment by fengmikaelson** [comment]
> > > 挺服的，就不能自己把auto_help.sh的参数改下？改完自动助力就生效了
> > 
> > 
> > 城城分现金没有自动助力吧？我记得不是要自己填的吗、
> 
> 有啊，只是lxk把里面的参数写错了，你多看看其他的issues就知道了，脚本里面多写一句sed -i，就解决了

卧槽？赶紧看看去。。。我还在手动加参数呢。。。

**Comment by dee-lii** [comment]
> > > 挺服的，就不能自己把auto_help.sh的参数改下？改完自动助力就体现了
> > 
> > 
> > 城城分现金没有自动助力吧？我记得不是要自己填的吗，
> 
> 有啊，只是lxk把里面的参数写错了，你多看看其他的问题就知道了，脚本里面多写一句sed -i，就解决了

老哥该把这个加到哪呢

**Comment by zhangj1024** [comment]
![image](https://user-images.githubusercontent.com/23623025/119942400-5aa21900-bfc4-11eb-9889-86599599653d.png)
除了你提供的助力码，还添加了其他的助力码，只是你的先助力，然后助力别人的

**Comment by dee-lii** [comment]
> ![图像](https://user-images.githubusercontent.com/23623025/119942400-5aa21900-bfc4-11eb-9889-86599599653d.png)
> 除了你提供的助力码，还添加了其他的助力码，只是你的先助力，然后助力别人的

老哥是不是把自动助力脚本里面的JD_CITY_EXCHANGE改成CITY_SHARECODES  就可以自动助力了
