### ISSUE TITLE
点点卷部分账号显示非法请求不能做任务，但APP上可以手动做任务

### ISSUE THREAD

**Issue by ranheqiao** [wisz2021/jd_docker#334]
![image](https://user-images.githubusercontent.com/43024843/119924753-c1183e80-bfa6-11eb-834f-5aaf36cd31c8.png)

**Comment by ssrgd** [comment]
我的点点卷也是这样

**Comment by wisz2021** [comment]
京东已在领取任务、签到、领取点点券三个添加了log做了校验，暂时无可解决
