### ISSUE TITLE
 jd_scripts代理设置后问题

### ISSUE THREAD

**Issue by 643406834** [wisz2021/jd_docker#336]
环境：docker装了clash和jd_scripts，jd_scripts的环境变量设置为：  
environment:
    - http_proxy=http://10.0.0.1:7880
    - HTTP_PROXY=http://10.0.0.1:7880
    - https_proxy=http://10.0.0.1:7880
    - HTTPS_PROXY=http://10.0.0.1:7880
 测试容器可以上外网，curl http://www.cip.cc   curl https://www.cip.cc  
jd_scripts窗口测试spnode jd_bean_sign.js命令，提示可以代理下载，不是cdn下载

问题：tg的bot可以使用，但bot功能比较简单，无法用更新cookies等其它操作
![image](https://user-images.githubusercontent.com/39716940/119931541-24f53400-bfb4-11eb-97c6-391e555a2457.png)
![image](https://user-images.githubusercontent.com/39716940/119931650-54a43c00-bfb4-11eb-8b17-bbddd7184521.png)

docker-comper配置：
![image](https://user-images.githubusercontent.com/39716940/119931947-f4fa6080-bfb4-11eb-9942-cf5648dcb949.png)
![image](https://user-images.githubusercontent.com/39716940/119931843-c11f3b00-bfb4-11eb-8615-d2e9ad6e47d6.png)

**Comment by lockingxp** [comment]
本来也不能更新ck？
老大故意不做的
做了只能便宜了微商
