### ISSUE TITLE
京东极速版红包抽奖限流

### ISSUE THREAD

**Issue by e-ivan** [wisz2021/jd_docker#337]
May 28 00:45:07 极速版签到提现：签到成功
May 28 00:45:07 
May 28 00:45:07 限流
May 28 00:45:08 限流
May 28 00:45:09 限流

这个是黑号了吗

**Comment by ssrgd** [comment]
但是实际又还能签到成功

**Comment by wisz2021** [comment]
改下cron运行。 默认是一天有运行两次的。 一次是0点， 一次是23点

**Comment by e-ivan** [comment]
> 
> 
> 改下cron运行。 默认是一天有运行两次的。 一次是0点， 一次是23点

我看了docker容器的自定义定时任务。好像只能追加我的新任务脚本。因为我是用的是默认的任务脚本，没有在自定义文件中写。有没有我追加自定义任务的同时，合并任务的时候，把仓库里的默认的同一个任务人家给禁掉。
这样就是直接在自定义任务里修改一些默认任务的执行时间。目前是因为默认的还会存在，所以0点，23点还会运行一次的，相当于没改
