### ISSUE TITLE
宠汪汪赛跑助力提示错误

### ISSUE THREAD

**Issue by JassonR** [wisz2021/jd_docker#339]
![image](https://user-images.githubusercontent.com/54344082/119945062-938fbd00-bfc7-11eb-8ddc-e7f030a1296f.png)

**Comment by lockingxp** [comment]
老大说了很多遍了
ios手机跑的能自动获取 不会出现这个
docker的需要读取服务器上的 服务器上是老大传上去的 因为有效期很短只有几个小时 就会出现你这种 只能换时间再试
后来提供了一个环境变量 供有能力获取tk的自己填写 
对不会的人很难而且需要一个root过的安卓机 不会就不要想了

**Comment by JassonR** [comment]
> 老大说了很多遍了
> ios手机跑的能自动获取 不会出现这个
> docker的需要读取服务器上的 服务器上是老大传上去的 因为有效期很短只有几个小时 就会出现你这种 只能换时间再试
> 后来提供了一个环境变量 供有能力获取tk的自己填写
> 对不会的人很难而且需要一个root过的安卓机 不会就不要想了

好的明白了 感谢回复
