### ISSUE TITLE
JD_DailyBonus.js 文件下载异常

### ISSUE THREAD

**Issue by TakcC** [wisz2021/jd_docker#340]
检测到您当前网络环境不能访问外网,将使用jsdelivr CDN下载JD_DailyBonus.js文件
JD_DailyBonus.js文件  CDN刷新成功
JD_DailyBonus.js 文件下载异常:RequestError: Client network socket disconnected before secure TLS connection was established

JD_DailyBonus.js 文件不存在，停止执行京东多合一签到

大佬们，这个怎么解决呢？

**Comment by wisz2021** [comment]
自己检查容器网络情况
