### ISSUE TITLE
pull 代码好像失败了

### ISSUE THREAD

**Issue by linyongfu2013** [wisz2021/jd_docker#35]
```
jd_scripts    | 设定远程仓库地址...
jd_scripts    | HEAD is now at 397a7268 default_task.sh update
jd_scripts    | git pull拉取最新代码...
jd_scripts    | remote: Enumerating objects: 99, done.
remote: Counting objects: 100% (99/99), done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 99 (delta 12), reused 85 (delta 6), pack-reused 0
Unpacking objects: 100% (99/99), 4.75 MiB | 43.00 KiB/s, done..00 KiB/s
jd_scripts    | From https://github.com/wisz2021/jd_docker
jd_scripts    |  + c24be516...61f5743a main       -> origin/main  (forced update)
jd_scripts    | Your configuration specifies to merge with the ref 'refs/heads/master'
jd_scripts    | from the remote, but no such ref was fetched.
```

docker-compose.yml 里仓库配置：- REPO_URL=https://github.com/wisz2021/jd_docker.git

**Comment by Au3C2** [comment]
> ```
> jd_scripts    | 设定远程仓库地址...
> jd_scripts    | HEAD is now at 397a7268 default_task.sh update
> jd_scripts    | git pull拉取最新代码...
> jd_scripts    | remote: Enumerating objects: 99, done.
> remote: Counting objects: 100% (99/99), done.
> remote: Compressing objects: 100% (93/93), done.
> remote: Total 99 (delta 12), reused 85 (delta 6), pack-reused 0
> Unpacking objects: 100% (99/99), 4.75 MiB | 43.00 KiB/s, done..00 KiB/s
> jd_scripts    | From https://github.com/wisz2021/jd_docker
> jd_scripts    |  + c24be516...61f5743a main       -> origin/main  (forced update)
> jd_scripts    | Your configuration specifies to merge with the ref 'refs/heads/master'
> jd_scripts    | from the remote, but no such ref was fetched.
> ```
> 
> docker-compose.yml 里仓库配置：- REPO_URL=https://github.com/wisz2021/jd_docker.git

`https://github.com/wisz2021/jd_docker.git` 这个仓库只是看教程用的，docker 配置仓库无需修改
