### ISSUE TITLE
请问怎么执行所有定时任务！

### ISSUE THREAD

**Issue by nomoneynolife** [wisz2021/jd_docker#4]
原因，昨天13：00停电到现在，很多任务都没跑，刚刚开机，怎么把所有定时任务执行一次！
感觉错失一个亿~

**Comment by SnorlaxX** [comment]
之前在gitee上看见别人写的
docker exec -it jd_scripts /bin/sh -c ' ls jd_*.js | grep -v jd_crazy_joy_coin.js |xargs -i node {}'
这个会漏一个jx_sign.js，要单独再执行一下

**Comment by nomoneynolife** [comment]
thank you sir!
