### ISSUE TITLE
企业微信应用推送报错， invalid access_token

### ISSUE THREAD

**Issue by csgitall** [wisz2021/jd_docker#49]
https://note.youdao.com/ynoteshare1/index.html?id=351e08a72378206f9dd64d2281e9b83b&type=note
参照以上文档设置的，python中单独post可以推送的，但是放入docker-compose.yml中就报错，具体配置如下，字母已缩写
    #企业微信应用通知
    - QYWX_AM="ww369,OM7eHQ,@all,1000004,2pV45dMIiZg"

**Comment by LongxianShi** [comment]
yml格式要求很严格的，查下是不是yml格式问题

**Comment by LongxianShi** [comment]
例如这个-

**Comment by LongxianShi** [comment]
-或者是缩进

**Comment by csgitall** [comment]
已解决，需要把前后引号去掉，前面主要是因为习惯性思维，字符串前后加引号
