### ISSUE TITLE
Docker容器内nodejs语法不支持~~~

### ISSUE THREAD

**Issue by xiaokaixuan** [wisz2021/jd_docker#5]
![image](https://user-images.githubusercontent.com/7234473/116499680-53adbb00-a8df-11eb-9436-a6fe53917f88.png)

**Comment by Vincentzhengwei** [comment]
更新node版本

**Comment by hys578084** [comment]
升级一下nodejs版本就可以了，不过我个人觉得作者修改脚本语法比较好一点，升级nodejs版本有时候非常慢而导致容器无node环境

**Comment by xiaokaixuan** [comment]
确实升级node版本就好了，起这个issue的主要目的是希望作者更新docker镜像内的node版本，一劳永逸啊...

**Comment by wisz2021** [comment]
@xiaokaixuan 我镜像的版本， 老早就更新了。 周一吧。

**Comment by wisz2021** [comment]
![image](https://user-images.githubusercontent.com/83346323/116500633-848eef80-a8e1-11eb-8d20-27e4120a6d84.png)

https://registry.hub.docker.com/r/lxk0301/jd_scripts

**Comment by hys578084** [comment]
> @xiaokaixuan 我镜像的版本， 老早就更新了。 周一吧。

我重构镜像之后的node版本好像还是没更新，姿势不对？😭

**Comment by xiaokaixuan** [comment]
> > @xiaokaixuan 我镜像的版本， 老早就更新了。 周一吧。
> 
> 我重构镜像之后的node版本好像还是没更新，姿势不对？

我也是 docker pull lxk0301/jd_scripts 之后 docker rm jd_scripts之后重建还是不行

**Comment by Vincentzhengwei** [comment]
虽然更新了，但pull之后，也更新了，但还是需要升级…

**Comment by gitupdate** [comment]
> > @xiaokaixuan 我镜像的版本， 老早就更新了。 周一吧。
> 
> 我重构镜像之后的node版本好像还是没更新，姿势不对？😭

看镜像是不是新的

**Comment by hys578084** [comment]
> > > @xiaokaixuan 我镜像的版本， 老早就更新了。 周一吧。
> > 
> > 
> > 我重构镜像之后的node版本好像还是没更新，姿势不对？😭
> 
> 看镜像是不是新的

镜像就是新的呀
![Uploading 7DFDAED0-0FEC-4A73-B7F3-CE5BCAC9E590.jpeg…]()

**Comment by xiaokaixuan** [comment]
@wisz2021 建议作者大佬 Dockerfile 继承自 FROM node:alpine3.12 保证nodejs为最新版。

**Comment by feiyu127** [comment]
@wisz2021 我看了下，你的DockerFile 是 FROM alpine:3.12
alpine:3.12 里的node 是12版本的，建议将这个升级到 3.13，里面的node版本就是14的了
这样应该就可以直接更新到node14了

**Comment by lddsb** [comment]
有什么快捷升级node的方法吗？

**Comment by Vincentzhengwei** [comment]
> 有什么快捷升级node的方法吗？

docker exec -it jd_scripts1 apk add nodejs-current;

或者进入容器里apk add nodejs-current;

**Comment by xiaokaixuan** [comment]
镜像已更新了

**Comment by VergLsm** [comment]
终于找到你们这群始作俑者了😂
把我们整惨了
https://github.com/wisz2021/jd_docker/issues/52#issuecomment-832102157

**Comment by xiaokaixuan** [comment]
@wisz2021 @VergLsm 怎么又改回去了 `alpine:3.12`里的node版本太低了，并不支持新语法，问题又出现了。
如果是因为armv7的原因，我建议基于`node:alpine3.12`镜像构建。

**Comment by VergLsm** [comment]
其实也可以在Dockerfile里面选择安装最新版本的node

**Comment by xiaokaixuan** [comment]
> 其实也可以在Dockerfile里面选择安装最新版本的node

`nodejs-current`也不算最新版吧  只能说是该系统下的下一个稳定版

**Comment by VergLsm** [comment]
能用不报错

**Comment by xiaokaixuan** [comment]
我意思 对于小白用户，能一劳永逸不是更好。万一后面又出现类似的问题。算了，我自己改下测试下提个PR。

**Comment by xiaokaixuan** [comment]
> 能用不报错

@VergLsm 有空的话 能否帮忙测试下armv7兼容性。#203

**Comment by wisz2021** [comment]
> @wisz2021 @VergLsm 怎么又改回去了 `alpine:3.12`里的node版本太低了，并不支持新语法，问题又出现了。
> 如果是因为armv7的原因，我建议基于`node:lts-alpine3.12`镜像构建。

已构建

**Comment by VergLsm** [comment]
> > 能用不报错
> 
> @VergLsm 有空的话 能否帮忙测试下armv7兼容性，我没armv7的设备。#203

在新的Dockerfile里去掉bash之后自己构建了一次，运行良好
