### ISSUE TITLE
4月30日的镜像在32位(armv7)架构无法启动

### ISSUE THREAD

**Issue by VergLsm** [wisz2021/jd_docker#52]
pull了新镜像之后，启动容器失败
~~查了一下估计是核心不支持某些包~~
原因是更新了alpine3.13 https://github.com/wisz2021/jd_docker/issues/52#issuecomment-832102157

快速解决办法：https://github.com/wisz2021/jd_docker/issues/52#issuecomment-832117046

```
npm install 安装最新依赖


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0xbeb4b12c
Illegal instruction (core dumped)
```

另外想提个建议，镜像能不能打个版本号啊，只有一个latest有点不方便，像这次启动失败之后我想倒退回之前的版本都没法了

**Comment by sanye5** [comment]
我也一样  树莓派的armv7  一直restarting  有办法解决吗大佬

**Comment by VergLsm** [comment]
@sanye5 放假没啥时间弄，在dockerhub找了个别人的旧的镜像装上临时解决，x86的镜像是正常的，粗略看了一下更新log也没动什么东西，就换了个底包，估计新的底包在armv7下有点问题

**Comment by VergLsm** [comment]
@sanye5 #60 为啥关闭了，问题解决了吗？

**Comment by sanye5** [comment]
> @sanye5 #60 为啥关闭了，问题解决了吗？

没有我刚刚可能网络不好无操作了   我换了你说的哪个  但是遇到了新问题
![Uploading QQ截图20210504111347.png…]()

**Comment by sanye5** [comment]
> @sanye5 #60 为啥关闭了，问题解决了吗？

大佬我加你下QQ咨询一下吧我动手能力有点差哈哈   我Q1505286062

**Comment by VergLsm** [comment]
深夜更一下，疑似问题根源在alpine3.13
https://github.com/alpinelinux/docker-alpine/issues/135
它要求使用64位时间，旨在兼容2038年以后的日期
影响范围包括所有32位架构的机器，造成更新4月30日镜像之后的日期异常和网络异常（pull不到源码，更新不了apk）
一些检查方法和解决办法在官网文档有写
https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements
顺便一提一下，不是只有这个项目踩坑了，很多项目也踩了
比如https://github.com/home-assistant/plugin-audio/issues/53
他们讨论里的解决办法跟官网一致
https://github.com/home-assistant/plugin-audio/issues/53#issuecomment-783258862

**Comment by VergLsm** [comment]
快速解决办法：回退到之前的版本
这里我自己使用的是```pm0n0/jd_scripts:4.16```这个镜像，目前运行良好，感谢pm0n0😂

至于nodejs版本的问题，直接一个```docker exec -it jd_scripts apk add nodejs-current;```解决

**Comment by scjean** [comment]
我也是树莓派，安装ubuntu64就行了，完美运行V4版

**Comment by sanye5** [comment]
> 我也是树莓派，安装ubuntu64就行了，完美运行V4版

是一个选择，我选择省事一点的回退脚本镜像版本

**Comment by stephenjoy1888** [comment]
> 我也是树莓派，安装ubuntu64就行了，完美运行V4版

v4版是什么

**Comment by VergLsm** [comment]
@scjean v4版是什么

**Comment by chrisyu714** [comment]
> 快速解决办法：回退到之前的版本
> 基于alpine3.12.7 构建镜像: `verglsm/jd_scripts:0.1` (nodejs 版本为 v14.5.0)

请问这个怎么用啊？

**Comment by gelei1210** [comment]
问题解决了吗 我的 玩客云armbian也不能跑了

**Comment by sanye5** [comment]
> 问题解决了吗 我的 玩客云armbian也不能跑了

解决了  用老版本镜像先

**Comment by wisz2021** [comment]
> 快速解决办法：回退到之前的版本
> 基于alpine3.12.7 构建镜像: `verglsm/jd_scripts:0.1` (nodejs 版本为 v14.5.0)
> 
> 5月8日更新 `verglsm/jd_scripts:0.2`

我退回这个版本。重新构建一下吧

**Comment by mrwuchangyu** [comment]
玩客云在docker-compose.yml 这个文件里面 第二行的image 改成  verglsm/jd_scripts:0.2  。改完后putty里面 docker-compose down && docker-compose pull && docker-compose up -d

**Comment by mrwuchangyu** [comment]
感谢VergLsm的指导

**Comment by cisco6005** [comment]
镜像昨天5月21号下午又出现错误了，npm各种报错，估计又有人改动代码了？

**Comment by VergLsm** [comment]
推荐使用官方最新镜像

**Comment by hewitt29** [comment]
jd v4镜像哪里还有吗
