### ISSUE TITLE
京东用户名包含中文，设置cookie的时候出现TypeError [ERR_INVALID_CHAR]，求助怎么解

### ISSUE THREAD

**Issue by ma-xin** [wisz2021/jd_docker#53]
"Invalid character in header content [\"cookie\"]"
京东多合一签到 API请求失败，请检查网路重试

‼️京东转盘-查询发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

**Comment by CC342** [comment]
> "Invalid character in header content ["cookie"]"
> 京东多合一签到 API请求失败，请检查网路重试
> 
> ‼️京东转盘-查询发生错误
> ‼️名称: Error
> ‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

我也是这个问题，而且是2天才找出原因的。pt_pin=xxx,这个xxx是中文就会出现api请求失败

**Comment by CC342** [comment]
> "Invalid character in header content ["cookie"]"
> 京东多合一签到 API请求失败，请检查网路重试
> 
> ‼️京东转盘-查询发生错误
> ‼️名称: Error
> ‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]
已成功。需要用插件读取ck，网页版F12的ck pin值是中文的，插件里面会转化成其他模式。

**Comment by ma-xin** [comment]
之前用的mac电脑，在开发者console窗口使用js语句复制出来的是中文，一直报这个错，
后来在window电脑上，同样的操作复制出来的中文是%E9%A9....，就没出现问题。
