### ISSUE TITLE
一直restarting状态

### ISSUE THREAD

**Issue by sanye5** [wisz2021/jd_docker#60]
如图  求懂得大佬解答
![QQ截图20210503223834](https://user-images.githubusercontent.com/34118626/116890527-4f2b2e80-ac60-11eb-9cbd-ba5a0efeba65.png)

**Comment by quanjindeng** [comment]
同样，一直重启，附上log
> 配置启用jd_crazy_joy_coin，杀掉jd_crazy_joy_coin任务，并重启
,配置jd_crazy_joy_coin重启完成
,第10步加载最新的定时任务文件...
,bot交互与spnode 前置条件成立，替换任务列表的node指令为spnode
,第11步将仓库的docker_entrypoint.sh脚本更新至系统/usr/local/bin/docker_entrypoint.sh内...
,发送通知
,--------------------------------------------------默认定时任务执行完成---------------------------------------------------
,启动crontab定时任务主进程...
,启动telegram bot指令交主进程...
,crond[86]: crond (busybox 1.32.1) started, log level 8
,2021-05-04 09:15:36,576-__main__-INFO=> [main] CRONTAB_LIST_FILE=crontab_list.sh 
,2021-05-04 09:15:36,580-apscheduler.scheduler-INFO=> [start] Scheduler started 
,Traceback (most recent call last):
,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 614, in urlopen
,    httplib_response = self._make_request(conn, method, url,
,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 360, in _make_request
,    self._validate_conn(conn)
,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 857, in _validate_conn
,    super(HTTPSConnectionPool, self)._validate_conn(conn)
,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 289, in _validate_conn
,    conn.connect()
,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 319, in connect
,    self.sock = ssl_wrap_socket(
,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
,    return context.wrap_socket(sock, server_hostname=server_hostname)
,  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
,    return self.sslsocket_class._create(
,  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
,    self.do_handshake()
,  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
,    self._sslobj.do_handshake()
,ConnectionResetError: [Errno 104] Connection reset by peer
,
,During handling of the above exception, another exception occurred:
,
,Traceback (most recent call last):
,  File "/usr/lib/python3.8/site-packages/telegram/utils/request.py", line 230, in _request_wrapper
,    resp = self._con_pool.request(*args, **kwargs)
,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 68, in request
,    return self.request_encode_body(method, url, fields=fields,
,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
,    return self.urlopen(method, url, **extra_kw)
,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
,    response = conn.urlopen(method, u.request_uri, **kw)
,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 665, in urlopen
,    retries = retries.increment(method, url, error=e, _pool=self,
,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
,    raise six.reraise(type(error), error, _stacktrace)
,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 685, in reraise
,    raise value.with_traceback(tb)
,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 614, in urlopen
,    httplib_response = self._make_request(conn, method, url,
,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 360, in _make_request
,    self._validate_conn(conn)
,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 857, in _validate_conn
,    super(HTTPSConnectionPool, self)._validate_conn(conn)
,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 289, in _validate_conn
,    conn.connect()
,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 319, in connect
,    self.sock = ssl_wrap_socket(
,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
,    return context.wrap_socket(sock, server_hostname=server_hostname)
,  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
,    return self.sslsocket_class._create(
,  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
,    self.do_handshake()
,  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
,    self._sslobj.do_handshake()
,telegram.vendor.ptb_urllib3.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
,
,During handling of the above exception, another exception occurred:
,
,Traceback (most recent call last):
,  File "/usr/bin/jd_bot", line 4, in <module>
,    __import__('pkg_resources').run_script('jd-scripts-bot==0.2', 'jd_bot')
,  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 651, in run_script
,    self.require(requires)[0].run_script(script_name, ns)
,  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1455, in run_script
,    exec(script_code, namespace, namespace)
,  File "/usr/lib/python3.8/site-packages/jd_scripts_bot-0.2-py3.8.egg/EGG-INFO/scripts/jd_bot", line 1114, in <module>
,  File "/usr/lib/python3.8/site-packages/jd_scripts_bot-0.2-py3.8.egg/EGG-INFO/scripts/jd_bot", line 1101, in main
,  File "/usr/lib/python3.8/site-packages/telegram/ext/updater.py", line 272, in start_polling
,    self._init_thread(self.dispatcher.start, "dispatcher", ready=dispatcher_ready)
,  File "/usr/lib/python3.8/site-packages/telegram/ext/updater.py", line 215, in _init_thread
,    name="Bot:{}:{}".format(self.bot.id, name),
,  File "/usr/lib/python3.8/site-packages/telegram/bot.py", line 62, in decorator
,    self.get_me()
,  File "/usr/lib/python3.8/site-packages/decorator.py", line 232, in fun
,    return caller(func, *(extras + args), **kw)
,  File "/usr/lib/python3.8/site-packages/telegram/bot.py", line 78, in decorator
,    result = func(*args, **kwargs)
,  File "/usr/lib/python3.8/site-packages/telegram/bot.py", line 326, in get_me
,    result = self._post('getMe', timeout=timeout, api_kwargs=api_kwargs)
,  File "/usr/lib/python3.8/site-packages/telegram/bot.py", line 184, in _post
,    return self.request.post('{}/{}'.format(self.base_url, endpoint), data=data,
,  File "/usr/lib/python3.8/site-packages/telegram/utils/request.py", line 325, in post
,    result = self._request_wrapper('POST', url,
,  File "/usr/lib/python3.8/site-packages/telegram/utils/request.py", line 236, in _request_wrapper
,    raise NetworkError('urllib3 HTTPError {}'.format(error))
,telegram.error.NetworkError: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
,

> 

![Screenshot_2021-05-04-09-21-09-38](https://user-images.githubusercontent.com/54259993/116951391-47987380-acba-11eb-8b62-0bbd0364ab79.jpg)

**Comment by ryan868** [comment]
你这个应该是树莓派吧 原因应该是更新包有不支持arm的东西 #52

**Comment by sanye5** [comment]
> 你这个应该是树莓派吧 原因应该是更新包有不支持arm的东西 #52

有什么补救措施嘛大佬

**Comment by sanye5** [comment]
> 同样，一直重启，附上log
> 
> > 配置启用jd_crazy_joy_coin，杀掉jd_crazy_joy_coin任务，并重启
> > ,配置jd_crazy_joy_coin重启完成
> > ,第10步加载最新的定时任务文件...
> > ,bot交互与spnode 前置条件成立，替换任务列表的node指令为spnode
> > ,第11步将仓库的docker_entrypoint.sh脚本更新至系统/usr/local/bin/docker_entrypoint.sh内...
> > ,发送通知
> > ,--------------------------------------------------默认定时任务执行完成---------------------------------------------------
> > ,启动crontab定时任务主进程...
> > ,启动telegram bot指令交主进程...
> > ,crond[86]: crond (busybox 1.32.1) started, log level 8
> > ,2021-05-04 09:15:36,576-**main**-INFO=> [main] CRONTAB_LIST_FILE=crontab_list.sh
> > ,2021-05-04 09:15:36,580-apscheduler.scheduler-INFO=> [start] Scheduler started
> > ,Traceback (most recent call last):
> > ,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 614, in urlopen
> > ,    httplib_response = self._make_request(conn, method, url,
> > ,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 360, in _make_request
> > ,    self._validate_conn(conn)
> > ,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 857, in _validate_conn
> > ,    super(HTTPSConnectionPool, self)._validate_conn(conn)
> > ,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 289, in _validate_conn
> > ,    conn.connect()
> > ,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 319, in connect
> > ,    self.sock = ssl_wrap_socket(
> > ,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
> > ,    return context.wrap_socket(sock, server_hostname=server_hostname)
> > ,  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
> > ,    return self.sslsocket_class._create(
> > ,  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
> > ,    self.do_handshake()
> > ,  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
> > ,    self._sslobj.do_handshake()
> > ,ConnectionResetError: [Errno 104] Connection reset by peer
> > ,
> > ,During handling of the above exception, another exception occurred:
> > ,
> > ,Traceback (most recent call last):
> > ,  File "/usr/lib/python3.8/site-packages/telegram/utils/request.py", line 230, in _request_wrapper
> > ,    resp = self._con_pool.request(*args, **kwargs)
> > ,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 68, in request
> > ,    return self.request_encode_body(method, url, fields=fields,
> > ,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
> > ,    return self.urlopen(method, url, **extra_kw)
> > ,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
> > ,    response = conn.urlopen(method, u.request_uri, **kw)
> > ,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 665, in urlopen
> > ,    retries = retries.increment(method, url, error=e, _pool=self,
> > ,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
> > ,    raise six.reraise(type(error), error, _stacktrace)
> > ,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 685, in reraise
> > ,    raise value.with_traceback(tb)
> > ,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 614, in urlopen
> > ,    httplib_response = self._make_request(conn, method, url,
> > ,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 360, in _make_request
> > ,    self._validate_conn(conn)
> > ,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 857, in _validate_conn
> > ,    super(HTTPSConnectionPool, self)._validate_conn(conn)
> > ,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 289, in _validate_conn
> > ,    conn.connect()
> > ,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 319, in connect
> > ,    self.sock = ssl_wrap_socket(
> > ,  File "/usr/lib/python3.8/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
> > ,    return context.wrap_socket(sock, server_hostname=server_hostname)
> > ,  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
> > ,    return self.sslsocket_class._create(
> > ,  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
> > ,    self.do_handshake()
> > ,  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
> > ,    self._sslobj.do_handshake()
> > ,telegram.vendor.ptb_urllib3.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
> > ,
> > ,During handling of the above exception, another exception occurred:
> > ,
> > ,Traceback (most recent call last):
> > ,  File "/usr/bin/jd_bot", line 4, in 
> > ,    **import**('pkg_resources').run_script('jd-scripts-bot==0.2', 'jd_bot')
> > ,  File "/usr/lib/python3.8/site-packages/pkg_resources/**init**.py", line 651, in run_script
> > ,    self.require(requires)[0].run_script(script_name, ns)
> > ,  File "/usr/lib/python3.8/site-packages/pkg_resources/**init**.py", line 1455, in run_script
> > ,    exec(script_code, namespace, namespace)
> > ,  File "/usr/lib/python3.8/site-packages/jd_scripts_bot-0.2-py3.8.egg/EGG-INFO/scripts/jd_bot", line 1114, in 
> > ,  File "/usr/lib/python3.8/site-packages/jd_scripts_bot-0.2-py3.8.egg/EGG-INFO/scripts/jd_bot", line 1101, in main
> > ,  File "/usr/lib/python3.8/site-packages/telegram/ext/updater.py", line 272, in start_polling
> > ,    self._init_thread(self.dispatcher.start, "dispatcher", ready=dispatcher_ready)
> > ,  File "/usr/lib/python3.8/site-packages/telegram/ext/updater.py", line 215, in _init_thread
> > ,    name="Bot:{}:{}".format(self.bot.id, name),
> > ,  File "/usr/lib/python3.8/site-packages/telegram/bot.py", line 62, in decorator
> > ,    self.get_me()
> > ,  File "/usr/lib/python3.8/site-packages/decorator.py", line 232, in fun
> > ,    return caller(func, *(extras + args), **kw)
> > ,  File "/usr/lib/python3.8/site-packages/telegram/bot.py", line 78, in decorator
> > ,    result = func(*args, **kwargs)
> > ,  File "/usr/lib/python3.8/site-packages/telegram/bot.py", line 326, in get_me
> > ,    result = self._post('getMe', timeout=timeout, api_kwargs=api_kwargs)
> > ,  File "/usr/lib/python3.8/site-packages/telegram/bot.py", line 184, in _post
> > ,    return self.request.post('{}/{}'.format(self.base_url, endpoint), data=data,
> > ,  File "/usr/lib/python3.8/site-packages/telegram/utils/request.py", line 325, in post
> > ,    result = self._request_wrapper('POST', url,
> > ,  File "/usr/lib/python3.8/site-packages/telegram/utils/request.py", line 236, in _request_wrapper
> > ,    raise NetworkError('urllib3 HTTPError {}'.format(error))
> > ,telegram.error.NetworkError: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
> > ,
> 
> > 
> 
> ![Screenshot_2021-05-04-09-21-09-38](https://user-images.githubusercontent.com/54259993/116951391-47987380-acba-11eb-8b62-0bbd0364ab79.jpg)

![image](https://user-images.githubusercontent.com/34118626/116953732-947f4880-acc0-11eb-92f6-1251a3e36023.png)
