### ISSUE TITLE
更新了4月30号的镜像之后在树莓派上运行不起来了，有没有老镜像能给我下一下的

### ISSUE THREAD

**Issue by Takicheng** [wisz2021/jd_docker#64]
更新了4月30号的镜像之后在树莓派上运行不起来了，一直重启，有没有老镜像能给我下一下的
顺便问下tg要怎么让他通网

**Comment by VergLsm** [comment]
可以试试 pm0n0/jd_scripts:4.16

**Comment by scjean** [comment]
我也是树莓派啊，可以运行的，没问题啊

**Comment by Takicheng** [comment]
> 我也是树莓派啊，可以运行的，没问题啊

镜像是用的4月30号的那个吗，我用那个容器一直重启

**Comment by 97xiami** [comment]
![Screenshot_20210505-101448.jpg](https://user-images.githubusercontent.com/26278263/117090376-bfce6a00-ad8a-11eb-96df-567986898256.jpg)

**Comment by VergLsm** [comment]
64位的请坐下 #52

**Comment by Takicheng** [comment]
> 可以试试`verglsm/jd_scripts:0.1`



> 64位的请坐下 #52

谢谢解答，我现在跑在腾讯云上了

**Comment by VergLsm** [comment]
@Takicheng 云函数？我试了一下部署不成功😂

**Comment by Takicheng** [comment]
> @Takicheng 云函数？我试了一下部署不成功😂

不是啊，之前活动买的三年的云服务器配置挺低的，早上试着装了docker可以跑起来，这个项目还有别的实现方法吗

**Comment by Takicheng** [comment]
> @Takicheng 云函数？我试了一下部署不成功😂

我现在只会各种地方装docker😂

**Comment by VergLsm** [comment]
@Takicheng 好像暂时就这两种，云函数自动部署好像现在还不好使了。
我还以为你买个服务器来薅羊毛呢😂
这种东西还是搞个arm板在家挂着踏实
不过日志写入和一天拉两次代码着实伤内存卡

**Comment by qq995764533** [comment]
> @Takicheng 好像暂时就这两种，云函数自动部署好像现在还不好使了。
> 我还以为你买个服务器来薅羊毛呢😂
> 这种东西还是搞个arm板在家挂着踏实
> 不过日志写入和一天拉两次代码着实伤内存卡

我就是租的亚马逊的服务器挂的。。挂路由太伤闪存了

**Comment by Takicheng** [comment]
> > @Takicheng 好像暂时就这两种，云函数自动部署好像现在还不好使了。
> > 我还以为你买个服务器来薅羊毛呢😂
> > 这种东西还是搞个arm板在家挂着踏实
> > 不过日志写入和一天拉两次代码着实伤内存卡
> 
> 我就是租的亚马逊的服务器挂的。。挂路由太伤闪存了

亚马逊的服务器便宜吗，可以直接连tg推送吗

**Comment by qq995764533** [comment]
> > > @Takicheng 好像暂时就这两种，云函数自动部署好像现在还不好使了。
> > > 我还以为你买个服务器来薅羊毛呢😂
> > > 这种东西还是搞个arm板在家挂着踏实
> > > 不过日志写入和一天拉两次代码着实伤内存卡
> > 
> > 
> > 我就是租的亚马逊的服务器挂的。。挂路由太伤闪存了
> 
> 亚马逊的服务器便宜吗，可以直接连tg推送吗

5刀一个月 可以买学生码 现在的学生码换算下来 512M运存大概是7块钱一个月吧 我租的日本的 当然可以直连tg 不过相对的 到国内这边的延迟比自己家里的高 但是服务器能做的事不止挂这个脚本 我只是本来就有用aws做其它事情 顺便挂这个
