### ISSUE TITLE
UA的格式和说明看不到了！

### ISSUE THREAD

**Issue by nodej622** [wisz2021/jd_docker#7]
老哥京东UA抓取了，填写格式没看到啊，烦请老哥给说下京东UA填写格式吧

**Comment by wisz2021** [comment]
UserAgent类似下面：
jdapp;iPhone;9.3.0;14.2;network/4g;Mozilla/5.0 (iPhone; CPU iPhone OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148;supportJDSHWK/1

**Comment by nodej622** [comment]
还得问下老哥，多账户指定ua的话，上面的格式我需要更改哪个呢？那个supportJDSHWK/1这个1更改为2吗，还是说前面userA1=变量加上数字呢？
