### ISSUE TITLE
TG_USER_ID怎么设置多个帐号

### ISSUE THREAD

**Issue by Ju-ch** [wisz2021/jd_docker#83]
请问如果希望多个人同时收到tg的通知，ID这里要怎么写才能正确识别多个。
```
TG_USER_ID＝***&***
TG_USER_ID＝***；***
TG_USER_ID＝***；&***

```

以上用法均告失败。

**Comment by Ju-ch** [comment]
放弃了，开始用pushplus推送了。

**Comment by wisz2021** [comment]
不行的。暂没有支持

**Comment by szweiw** [comment]
> 
> 
> 请问如果希望多个人同时收到tg的通知，ID这里要怎么写才能正确识别多个。
> 
> ```
> TG_USER_ID＝***&***
> TG_USER_ID＝***；***
> TG_USER_ID＝***；&***
> ```
> 
> 以上用法均告失败。

正确的做法不是应该把消息机器人和所有接收消息的人，在TG里面组成一个群吗。
