### ISSUE TITLE
美丽研究院403，请教下这个怎么解决

### ISSUE THREAD

**Issue by c526796017** [wisz2021/jd_docker#86]
![image](https://user-images.githubusercontent.com/41948565/117387146-de636b00-af1a-11eb-9102-9420ab1bf37d.png)
请教下各位老哥这种情况怎么处理

**Comment by qiuzhongqiang** [comment]
附议，请大佬指教。

**Comment by kissfast** [comment]
最后一行的提示，不是说的很清楚了么？

**Comment by c526796017** [comment]
> 最后一行的提示，不是说的很清楚了么？

请教下老哥，怎么设置域名直连，腾讯云的，百度一直没有搜到。。

**Comment by c526796017** [comment]
> 最后一行的提示，不是说的很清楚了么？

容器内ping 这个域名是通的
