### ISSUE TITLE
两个活动需要更新

### ISSUE THREAD

**Issue by danwangshimoluo** [wisz2021/jd_docker#88]
1.脚本 jd_speed_redpocke.js  （新一期，5.6-5.30）
2.新一期的京东国际环球挑战赛 对应脚本  jd_global.js （04.28-05.28）

**Comment by wisz2021** [comment]
活动一 已经更新。
活动二。收益太低。没有弄了。而且京东加了其他验证方式。和之前的不一样。需要解决挺久的
