### ISSUE TITLE
群晖下,用的默认单容器多账号,自动互助的这个命令- ENABLE_AUTO_HELP=true 添加在哪啊,有人告知下么,多谢

### ISSUE THREAD

**Issue by LLLOOO3214** [wisz2021/jd_docker#91]
- 我的环境是群晖Docker,用的是这个jd_scripts.syno.json,启动的容器
- 就是想问- ENABLE_AUTO_HELP=true 这个命令行添加在jd_scripts.syno.json这个文件里的哪个位置
- 谢谢

**Comment by wisz2021** [comment]
> * 我的环境是群晖Docker,用的是这个jd_scripts.syno.json,启动的容器
> * 就是想问- ENABLE_AUTO_HELP=true 这个命令行添加在jd_scripts.syno.json这个文件里的哪个位置
> * 谢谢

和你其他环境变量一样的写法。

**Comment by LLLOOO3214** [comment]
jd_scripts.syno.json我用的是默认的.只是添加了cookies,能具体说一下- ENABLE_AUTO_HELP=true 这个命令行添加在jd_scripts.syno.json这个文件里的哪个位置么
