### ISSUE TITLE
speed_sign脚本，能不能把邀请放出来？

### ISSUE THREAD

**Issue by taylorSZSS** [wisz2021/jd_docker#93]
极速版签到实际有执行邀请，却不输出任何日志，内置楼主的，能不能放出让至环境变量让我们配置。

**Comment by twfeiyu** [comment]
别想,为爱发电呢.
极速版有邀请新奖励.3000金币, 一年金币分成,50元金币兑换红包.看起来不大,海量基数下~~~

**Comment by wisz2021** [comment]
请见谅

![D3C9E5F5-C10D-49C6-AF26-52A9ED09A4F7](https://user-images.githubusercontent.com/83346323/117520337-504eb980-afda-11eb-8695-fc4863932974.jpeg)

**Comment by ICEOOX** [comment]
> 极速版签到实际有执行邀请，却不输出任何日志，内置楼主的，能不能放出让至环境变量让我们配置。

极速版作者并没有内置邀请
金币找到自己的邀请，手动被邀请就可以了。

作者没有内置邀请 ！
作者没有内置邀请 ！
 作者没有内置邀请！

**Comment by taylorSZSS** [comment]
> > 极速版签到实际有执行邀请，却不输出任何日志，内置楼主的，能不能放出让至环境变量让我们配置。
> 
> 极速版作者并没有内置邀请
> 金币找到自己的邀请，手动被邀请就可以了。
> 
> 作者没有内置邀请 ！
> 作者没有内置邀请 ！
> 作者没有内置邀请！

已经close了，没必要回复我了，自己自信看代码，隐藏邀请console.log的输出，再去金币获取记录看看是不是有被邀请+100金币，我不懂你来怼我干嘛。怼我之前看看事实再来

**Comment by ICEOOX** [comment]
> 极速版签到实际有执行邀请，却不输出任何日志，内置楼主的，能不能放出让至环境变量让我们配置。

极速版作者并没有内置邀请
金币找到自己的邀请，手动被邀请就可以了。

作者没有内置邀请 ！
作者没有内置邀请 ！
 作者没有内置邀请！

> > > 极速版签到实际有执行邀请，却不输出任何日志，内置楼主的，能不能放出让至环境变量让我们配置。
> > 
> > 
> > 极速版作者并没有内置邀请
> > 金币找到自己的邀请，手动被邀请就可以了。
> > 作者没有内置邀请 ！
> > 作者没有内置邀请 ！
> > 作者没有内置邀请！
> 
> 已经close了，没必要回复我了，自己自信看代码，隐藏邀请console.log的输出，再去金币获取记录看看是不是有被邀请+100金币，我不懂你来怼我干嘛。怼我之前看看事实再来

没人怼你，只能说少搭理你这种人，也不知道你用的谁的镜像，我10个号码，运行3个月，到今天看到你的议题，我才手动去做邀请，还能够做的上，9个号全被主号邀请成功，证明极速脚本不存在内置邀请。

对于你这种傻瓜，不是自己懂点东西就瞎说。要不就是用的别人盗版镜像被改了。要不就是自己看错了，脚本本来加密的，请问你解密了吗？

本来好心告诉你而已，你看看你那副嘴脸，真让人恶心！

**Comment by taylorSZSS** [comment]
> > 极速版签到实际有执行邀请，却不输出任何日志，内置楼主的，能不能放出让至环境变量让我们配置。
> 
> 极速版作者并没有内置邀请
> 金币找到自己的邀请，手动被邀请就可以了。
> 
> 作者没有内置邀请 ！
> 作者没有内置邀请 ！
> 作者没有内置邀请！
> 
> > > > 极速版签到实际有执行邀请，却不输出任何日志，内置楼主的，能不能放出让至环境变量让我们配置。
> > > 
> > > 
> > > 极速版作者并没有内置邀请
> > > 金币找到自己的邀请，手动被邀请就可以了。
> > > 作者没有内置邀请 ！
> > > 作者没有内置邀请 ！
> > > 作者没有内置邀请！
> > 
> > 
> > 已经close了，没必要回复我了，自己自信看代码，隐藏邀请console.log的输出，再去金币获取记录看看是不是有被邀请+100金币，我不懂你来怼我干嘛。怼我之前看看事实再来
> 
> 没人怼你，只能说少搭理你这种人，也不知道你用的谁的镜像，我10个号码，运行3个月，到今天看到你的议题，我才手动去做邀请，还能够做的上，9个号全被主号邀请成功，证明极速脚本不存在内置邀请。
> 
> 对于你这种傻瓜，不是自己懂点东西就瞎说。要不就是用的别人盗版镜像被改了。要不就是自己看错了，脚本本来加密的，请问你解密了吗？
> 
> 本来好心告诉你而已，你看看你那副嘴脸，真让人恶心！
用的是E大的镜像，有问题？都是群里的，没证据我会瞎说，跟你在这边喷没意思。TG群里你说哪位可以@我一下，证据发你看

**Comment by taylorSZSS** [comment]
> > > 极速版签到实际有执行邀请，却不输出任何日志，内置楼主的，能不能放出让至环境变量让我们配置。
> > 
> > 
> > 极速版作者并没有内置邀请
> > 金币找到自己的邀请，手动被邀请就可以了。
> > 作者没有内置邀请 ！
> > 作者没有内置邀请 ！
> > 作者没有内置邀请！
> > > > > 极速版签到实际有执行邀请，却不输出任何日志，内置楼主的，能不能放出让至环境变量让我们配置。
> > > > 
> > > > 
> > > > 极速版作者并没有内置邀请
> > > > 金币找到自己的邀请，手动被邀请就可以了。
> > > > 作者没有内置邀请 ！
> > > > 作者没有内置邀请 ！
> > > > 作者没有内置邀请！
> > > 
> > > 
> > > 已经close了，没必要回复我了，自己自信看代码，隐藏邀请console.log的输出，再去金币获取记录看看是不是有被邀请+100金币，我不懂你来怼我干嘛。怼我之前看看事实再来
> > 
> > 
> > 没人怼你，只能说少搭理你这种人，也不知道你用的谁的镜像，我10个号码，运行3个月，到今天看到你的议题，我才手动去做邀请，还能够做的上，9个号全被主号邀请成功，证明极速脚本不存在内置邀请。
> > 对于你这种傻瓜，不是自己懂点东西就瞎说。要不就是用的别人盗版镜像被改了。要不就是自己看错了，脚本本来加密的，请问你解密了吗？
> > 本来好心告诉你而已，你看看你那副嘴脸，真让人恶心！
> > 用的是E大的镜像，有问题？都是群里的，没证据我会瞎说，跟你在这边喷没意思。TG群里你说哪位可以@我一下，证据发你看，况且，你玩得也没我久啊，我还有97个号呢，也没我多啊，动不动说别人傻瓜，说我这副嘴脸？请问我说你啥了嘛？你明天再试试晚上能不能助力上，而且我说的助力是极速版--佰元生活费--赚金币--邀请好友。

**Comment by ICEOOX** [comment]
> > > > > 极速版签到实际有执行邀请，却不输出任何日志，内置楼主的，能不能放出让至环境变量让我们配置。
> > > > 
> > > > 
> > > > 极速版作者并没有内置邀请
> > > > 金币找到自己的邀请，手动被邀请就可以了。
> > > > 作者没有内置邀请 ！
> > > > 作者没有内置邀请 ！
> > > > 作者没有内置邀请！
> > > > > > > 极速版签到实际有执行邀请，却不输出任何日志，内置楼主的，能不能放出让至环境变量让我们配置。
> > > > > > 
> > > > > > 
> > > > > > 极速版作者并没有内置邀请
> > > > > > 金币找到自己的邀请，手动被邀请就可以了。
> > > > > > 作者没有内置邀请 ！
> > > > > > 作者没有内置邀请 ！
> > > > > > 作者没有内置邀请！
> > > > > 
> > > > > 
> > > > > 已经close了，没必要回复我了，自己自信看代码，隐藏邀请console.log的输出，再去金币获取记录看看是不是有被邀请+100金币，我不懂你来怼我干嘛。怼我之前看看事实再来
> > > > 
> > > > 
> > > > 没人怼你，只能说少搭理你这种人，也不知道你用的谁的镜像，我10个号码，运行3个月，到今天看到你的议题，我才手动去做邀请，还能够做的上，9个号全被主号邀请成功，证明极速脚本不存在内置邀请。
> > > > 对于你这种傻瓜，不是自己懂点东西就瞎说。要不就是用的别人盗版镜像被改了。要不就是自己看错了，脚本本来加密的，请问你解密了吗？
> > > > 本来好心告诉你而已，你看看你那副嘴脸，真让人恶心！
> > > > 用的是E大的镜像，有问题？都是群里的，没证据我会瞎说，跟你在这边喷没意思。TG群里你说哪位可以@我一下，证据发你看，况且，你玩得也没我久啊，我还有97个号呢，也没我多啊，动不动说别人傻瓜，说我这副嘴脸？请问我说你啥了嘛？你明天再试试晚上能不能助力上，而且我说的助力是极速版--佰元生活费--赚金币--邀请好友。你看看是不是同一个

嘛玩意？97个号？一个人哪来的这么多号？一个身份证可以注册几个号？一个镜像最大也才12个号，你哪来的那么多手机号？实名制全国一怔才5号，你不是倒卖呢吧

**Comment by taylorSZSS** [comment]
> > > > > > 极速版签到实际有执行邀请，却不输出任何日志，内置楼主的，能不能放出让至环境变量让我们配置。
> > > > > 
> > > > > 
> > > > > 极速版作者并没有内置邀请
> > > > > 金币找到自己的邀请，手动被邀请就可以了。
> > > > > 作者没有内置邀请 ！
> > > > > 作者没有内置邀请 ！
> > > > > 作者没有内置邀请！
> > > > > > > > 极速版签到实际有执行邀请，却不输出任何日志，内置楼主的，能不能放出让至环境变量让我们配置。
> > > > > > > 
> > > > > > > 
> > > > > > > 极速版作者并没有内置邀请
> > > > > > > 金币找到自己的邀请，手动被邀请就可以了。
> > > > > > > 作者没有内置邀请 ！
> > > > > > > 作者没有内置邀请 ！
> > > > > > > 作者没有内置邀请！
> > > > > > 
> > > > > > 
> > > > > > 已经close了，没必要回复我了，自己自信看代码，隐藏邀请console.log的输出，再去金币获取记录看看是不是有被邀请+100金币，我不懂你来怼我干嘛。怼我之前看看事实再来
> > > > > 
> > > > > 
> > > > > 没人怼你，只能说少搭理你这种人，也不知道你用的谁的镜像，我10个号码，运行3个月，到今天看到你的议题，我才手动去做邀请，还能够做的上，9个号全被主号邀请成功，证明极速脚本不存在内置邀请。
> > > > > 对于你这种傻瓜，不是自己懂点东西就瞎说。要不就是用的别人盗版镜像被改了。要不就是自己看错了，脚本本来加密的，请问你解密了吗？
> > > > > 本来好心告诉你而已，你看看你那副嘴脸，真让人恶心！
> > > > > 用的是E大的镜像，有问题？都是群里的，没证据我会瞎说，跟你在这边喷没意思。TG群里你说哪位可以@我一下，证据发你看，况且，你玩得也没我久啊，我还有97个号呢，也没我多啊，动不动说别人傻瓜，说我这副嘴脸？请问我说你啥了嘛？你明天再试试晚上能不能助力上，而且我说的助力是极速版--佰元生活费--赚金币--邀请好友。你看看是不是同一个
> 
> 嘛玩意？97个号？一个人哪来的这么多号？一个身份证可以注册几个号？一个镜像最大也才12个号，你哪来的那么多手机号？实名制全国一怔才5号，你不是倒卖呢吧

所以你现在就是想怼我是吧？转移话题呢？不是在扯邀请的问题嘛，实名制只能我只能认证3个号，不知道你怎么弄的五个号。多容器都不会？我在lxk的tg群里，他们都知道我哪来的号，轮到你质疑了？倒卖？对不起不需要，都是同事朋友同学。

**Comment by taylorSZSS** [comment]
ddd

**Comment by taylorSZSS** [comment]
> > > > > > 极速版签到实际有执行邀请，却不输出任何日志，内置楼主的，能不能放出让至环境变量让我们配置。
> > > > > 
> > > > > 
> > > > > 极速版作者并没有内置邀请
> > > > > 金币找到自己的邀请，手动被邀请就可以了。
> > > > > 作者没有内置邀请 ！
> > > > > 作者没有内置邀请 ！
> > > > > 作者没有内置邀请！
> > > > > > > > 极速版签到实际有执行邀请，却不输出任何日志，内置楼主的，能不能放出让至环境变量让我们配置。
> > > > > > > 
> > > > > > > 
> > > > > > > 极速版作者并没有内置邀请
> > > > > > > 金币找到自己的邀请，手动被邀请就可以了。
> > > > > > > 作者没有内置邀请 ！
> > > > > > > 作者没有内置邀请 ！
> > > > > > > 作者没有内置邀请！
> > > > > > 
> > > > > > 
> > > > > > 已经close了，没必要回复我了，自己自信看代码，隐藏邀请console.log的输出，再去金币获取记录看看是不是有被邀请+100金币，我不懂你来怼我干嘛。怼我之前看看事实再来
> > > > > 
> > > > > 
> > > > > 没人怼你，只能说少搭理你这种人，也不知道你用的谁的镜像，我10个号码，运行3个月，到今天看到你的议题，我才手动去做邀请，还能够做的上，9个号全被主号邀请成功，证明极速脚本不存在内置邀请。
> > > > > 对于你这种傻瓜，不是自己懂点东西就瞎说。要不就是用的别人盗版镜像被改了。要不就是自己看错了，脚本本来加密的，请问你解密了吗？
> > > > > 本来好心告诉你而已，你看看你那副嘴脸，真让人恶心！
> > > > > 用的是E大的镜像，有问题？都是群里的，没证据我会瞎说，跟你在这边喷没意思。TG群里你说哪位可以@我一下，证据发你看，况且，你玩得也没我久啊，我还有97个号呢，也没我多啊，动不动说别人傻瓜，说我这副嘴脸？请问我说你啥了嘛？你明天再试试晚上能不能助力上，而且我说的助力是极速版--佰元生活费--赚金币--邀请好友。你看看是不是同一个
> 
> 嘛玩意？97个号？一个人哪来的这么多号？一个身份证可以注册几个号？一个镜像最大也才12个号，你哪来的那么多手机号？实名制全国一怔才5号，你不是倒卖呢吧

问题关闭了，有需要交流我们添加好友说
