### ISSUE TITLE
git拉取时遇到的问题

### ISSUE THREAD

**Issue by 1910054472** [wisz2021/jd_docker#94]
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
ERROR: We're doing an SSH key audit.
Reason: unverified automatically (private key found in a public repository)
Please visit https://github.com/settings/keys/51608064
to approve this key so we know it's safe.

Fingerprint:
SHA256:Xd+RWODOBbpSA34RbpD3Whg70OUsynFdJdTxGRobR6w

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by 1910054472** [comment]
已解决

**Comment by baby195lxl** [comment]
> 已解决

请问你是怎么解决的啊，谢谢了
