### ISSUE TITLE
一个容器多账户问题

### ISSUE THREAD

**Issue by crazyzzcc** [wisz2021/jd_docker#96]
我按照环境变量说明里的配置的：
在docker-compose.yml配置文件中- JD_COOKIE=pt_key=XXX;pt_pin=XXX;&pt_key=XXX;pt_pin=XXX;&pt_key=XXX;pt_pin=XXX;
但是容器总是不停重启是为什么呢，请大神指导
我是win10系统

**Comment by X-Mars** [comment]
跟你配置无关，git仓库出问题了。等等吧

**Comment by crazyzzcc** [comment]
> 跟你配置无关，git仓库出问题了。等等吧

谢谢
